function toggleMenu(){document.querySelector('.navlinks').classList.toggle('open')}
function setupAccordions(){document.querySelectorAll('.accordion button').forEach(btn=>{btn.addEventListener('click',()=>{const p=btn.nextElementSibling;p.style.display=p.style.display==='block'?'none':'block';btn.setAttribute('aria-expanded',p.style.display==='block')})})}
function openTab(evt, id){document.querySelectorAll('.tab-content').forEach(el=>el.classList.remove('active'));document.querySelectorAll('.tab-button').forEach(el=>el.classList.remove('active'));document.getElementById(id).classList.add('active');evt.currentTarget.classList.add('active')}
function openModal(id){document.getElementById(id).style.display='block'}
function closeModal(id){document.getElementById(id).style.display='none'}
window.onclick=function(e){document.querySelectorAll('.modal').forEach(m=>{if(e.target==m)m.style.display='none'})}
function filterCards(){const q=(document.getElementById('searchInput')?.value||'').toLowerCase();const kind=(document.getElementById('kindFilter')?.value||'all');document.querySelectorAll('[data-card]').forEach(card=>{const text=card.innerText.toLowerCase();const k=card.dataset.kind;card.style.display=(text.includes(q)&&(kind==='all'||kind===k))?'block':'none'})}
function filterTable(){const q=(document.getElementById('tableSearch')?.value||'').toLowerCase();document.querySelectorAll('#dataTable tbody tr').forEach(row=>{row.style.display=row.innerText.toLowerCase().includes(q)?'':'none'})}
let slideIndex=0;function showSlide(n){const slides=document.querySelectorAll('.institutional-slideshow .slide');const dots=document.querySelectorAll('.institutional-slideshow .dot');if(!slides.length)return;slideIndex=(n+slides.length)%slides.length;slides.forEach(s=>s.classList.remove('active'));dots.forEach(d=>d.classList.remove('active'));slides[slideIndex].classList.add('active');if(dots[slideIndex])dots[slideIndex].classList.add('active')}function nextSlide(delta){showSlide(slideIndex+delta)}
function setupBackTop(){const b=document.querySelector('.backtop');if(!b)return;window.addEventListener('scroll',()=>{b.style.display=window.scrollY>600?'inline-flex':'none'})}
function announcePoint(name){const box=document.getElementById('mapInfo'); if(box) box.innerHTML='<strong>'+name+'</strong><br>Questo punto mostra la posizione approssimativa nel progetto. Apri la scheda item o la mappa OSM per il dettaglio.'}
window.addEventListener('DOMContentLoaded',()=>{
  setupAccordions();
  setupBackTop();
  setupLanguageSwitcher();
  applyLanguage(localStorage.getItem('preferredLanguage') || 'it');
  showSlide(0);

  const slideshow = document.querySelector('.institutional-slideshow');
  const slides = document.querySelectorAll('.institutional-slideshow .slide');
  if (slideshow && slides.length > 1) {
    let autoSlideTimer = setInterval(()=>nextSlide(1), 5000);

    // Pausa al passaggio del mouse, così l'utente può leggere la card.
    slideshow.addEventListener('mouseenter', ()=>clearInterval(autoSlideTimer));
    slideshow.addEventListener('mouseleave', ()=>{
      autoSlideTimer = setInterval(()=>nextSlide(1), 5000);
    });
  }
})



/* --- Trilingual interface: IT / 中文 / EN --- */
const I18N = {
  "zh": {
    "Patrimoni in Dialogo": "对话中的遗产",
    "Rete digitale Cina–Italia": "中意文化遗产数字网络",
    "Home": "首页",
    "Catalogo ▾": "目录 ▾",
    "Catalogo": "目录",
    "Mappa": "地图",
    "Timeline": "时间线",
    "Dati": "数据",
    "Componenti": "组件",
    "Scarica CSV": "下载 CSV",
    "Scarica JSON": "下载 JSON",
    "Apri scheda": "打开条目",
    "Apri la fonte": "打开来源",
    "Fonte": "来源",
    "Fonte ufficiale": "官方来源",
    "Cina": "中国",
    "Italia": "意大利",
    "Tutti i paesi": "全部国家",
    "Patrimonio Mondiale UNESCO": "UNESCO 世界遗产",
    "Lista Tentativa UNESCO": "UNESCO 预备名单",
    "Contesto del gemellaggio": "结好关系背景",
    "Quadro istituzionale del progetto": "项目的制度背景",
    "Gemellaggio come relazione culturale": "作为文化关系的结好",
    "Continuità tra siti e città": "遗产地与城市关系的延续",
    "Dialogo al più alto livello": "高层对话",
    "Forum di Hangzhou": "杭州论坛",
    "Avvio della rete UNESCO": "UNESCO 网络的启动",
    "Nota metodologica:": "方法说明：",
    "Vai alla timeline completa": "查看完整时间线",
    "Tre relazioni principali": "三组核心关系",
    "Item principali": "主要条目",
    "Architettura del sito": "网站结构",
    "Catalogo degli item": "条目目录",
    "Navigazione attiva per ricerca libera e filtro per paese. Le schede sono ordinate per coppie verticali di gemellaggio: vie storiche, giardini d’acqua e paesaggi urbani lagunari.": "可通过自由搜索和国家筛选进行浏览。卡片按三组垂直配对关系排列：历史道路、水景园林与潟湖城市景观。",
    "Mappa eurasiatica dei gemellaggi": "中意结好关系的欧亚地图",
    "Navigazione spaziale interattiva": "互动空间导航",
    "Passa il mouse sulle stelle per vedere una scheda mobile; clicca per fissare una card informativa con il link alla scheda item.": "将鼠标悬停在五角星上可查看浮动卡片；点击可固定信息卡，并进入对应条目页面。",
    "Relazione di gemellaggio": "结好关系",
    "Tre coppie patrimoniali": "三组遗产配对",
    "Mappe dettagliate": "详细地图",
    "Cronologia della rete patrimoniale": "遗产网络时间线",
    "Accesso temporale alla collezione": "藏品的时间型访问方式",
    "Come leggere la timeline": "如何阅读时间线",
    "Vedi il catalogo": "查看目录",
    "Vedi la mappa": "查看地图",
    "Vedi i dati": "查看数据",
    "Nota di selezione": "筛选说明",
    "Tabella dei dati": "数据表",
    "Cerca nella tabella": "在表格中搜索",
    "Componenti e strumenti usati": "使用的组件与工具",
    "Idea progettuale": "项目理念",
    "CSV": "CSV",
    "JSON": "JSON",
    "Dublin Core XML": "Dublin Core XML",
    "TEI XML": "TEI XML",
    "Paese": "国家",
    "Periodo storico": "历史时期",
    "Parole chiave": "关键词",
    "Seleziona una stella": "选择一颗五角星",
    "Clicca su un patrimonio per visualizzare nome, paese, periodo storico e parole chiave.": "点击一个遗产点，查看名称、国家、历史时期与关键词。",
    "Apri scheda item": "打开条目页面",
    "↑ Top": "↑ 顶部",
    "Cerca per nome, luogo, tema…": "按名称、地点、主题搜索……",
    "Shudao": "蜀道 Shudao",
    "Palazzo d’Estate": "颐和园 Palazzo d’Estate",
    "Giardini classici di Suzhou": "苏州古典园林 Giardini classici di Suzhou",
    "Venezia e la sua Laguna": "威尼斯及其潟湖 Venezia e la sua Laguna",
    "Via Appia. Regina Viarum": "阿皮亚古道 Via Appia",
    "Villa d’Este, Tivoli": "埃斯特别墅 Villa d’Este",
    "Vie storiche": "历史道路",
    "Giardini e acqua": "园林与水",
    "Città d’acqua e giardini": "水城与园林",
    "Una rete digitale per descrivere, navigare e interpretare le relazioni fra siti culturali cinesi e italiani: vie storiche, giardini d’acqua e città d’acqua.": "一个用于描述、浏览和解释中意文化遗产关系的数字网络：历史道路、水景园林与水城。",
    "Esplora il catalogo": "浏览目录",
    "Apri la mappa": "打开地图",
    "Idea del progetto": "项目理念",
    "Il progetto non presenta soltanto sei luoghi patrimoniali: li trasforma in una collezione digitale strutturata, composta da item, metadati, fonti autorevoli, dati geografici e relazioni tipizzate.": "本项目并非只展示六处遗产地，而是将它们转化为一个结构化数字集合，由条目、元数据、权威来源、地理数据和类型化关系组成。",
    "Progetto didattico per Digital Humanities e Patrimonio Culturale.": "Digital Humanities e Patrimonio Culturale 课程项目。"
  },
  "en": {
    "Patrimoni in Dialogo": "Heritages in Dialogue",
    "Rete digitale Cina–Italia": "China–Italy Digital Heritage Network",
    "Home": "Home",
    "Catalogo ▾": "Catalogue ▾",
    "Catalogo": "Catalogue",
    "Mappa": "Map",
    "Timeline": "Timeline",
    "Dati": "Data",
    "Componenti": "Components",
    "Scarica CSV": "Download CSV",
    "Scarica JSON": "Download JSON",
    "Apri scheda": "Open record",
    "Apri la fonte": "Open source",
    "Fonte": "Source",
    "Fonte ufficiale": "Official source",
    "Cina": "China",
    "Italia": "Italy",
    "Tutti i paesi": "All countries",
    "Patrimonio Mondiale UNESCO": "UNESCO World Heritage",
    "Lista Tentativa UNESCO": "UNESCO Tentative List",
    "Contesto del gemellaggio": "Twinning Context",
    "Quadro istituzionale del progetto": "Institutional Framework of the Project",
    "Gemellaggio come relazione culturale": "Twinning as a Cultural Relation",
    "Continuità tra siti e città": "Continuity between Sites and Cities",
    "Dialogo al più alto livello": "High-level Dialogue",
    "Forum di Hangzhou": "Hangzhou Forum",
    "Avvio della rete UNESCO": "Launch of the UNESCO Network",
    "Nota metodologica:": "Methodological note:",
    "Vai alla timeline completa": "Go to the full timeline",
    "Tre relazioni principali": "Three Main Relations",
    "Item principali": "Main Items",
    "Architettura del sito": "Site Architecture",
    "Catalogo degli item": "Item Catalogue",
    "Navigazione attiva per ricerca libera e filtro per paese. Le schede sono ordinate per coppie verticali di gemellaggio: vie storiche, giardini d’acqua e paesaggi urbani lagunari.": "Active navigation through free search and country filter. Records are arranged by vertical twinning pairs: historic routes, water gardens, and lagoon urban landscapes.",
    "Mappa eurasiatica dei gemellaggi": "Eurasian Map of Twinnings",
    "Navigazione spaziale interattiva": "Interactive Spatial Navigation",
    "Passa il mouse sulle stelle per vedere una scheda mobile; clicca per fissare una card informativa con il link alla scheda item.": "Hover over the stars to view a floating card; click to pin an information card with a link to the item record.",
    "Relazione di gemellaggio": "Twinning relation",
    "Tre coppie patrimoniali": "Three Heritage Pairs",
    "Mappe dettagliate": "Detailed Maps",
    "Cronologia della rete patrimoniale": "Chronology of the Heritage Network",
    "Accesso temporale alla collezione": "Temporal Access to the Collection",
    "Come leggere la timeline": "How to Read the Timeline",
    "Vedi il catalogo": "View catalogue",
    "Vedi la mappa": "View map",
    "Vedi i dati": "View data",
    "Nota di selezione": "Selection note",
    "Tabella dei dati": "Data Table",
    "Cerca nella tabella": "Search the table",
    "Componenti e strumenti usati": "Components and Tools Used",
    "Idea progettuale": "Project Idea",
    "CSV": "CSV",
    "JSON": "JSON",
    "Dublin Core XML": "Dublin Core XML",
    "TEI XML": "TEI XML",
    "Paese": "Country",
    "Periodo storico": "Historical period",
    "Parole chiave": "Keywords",
    "Seleziona una stella": "Select a star",
    "Clicca su un patrimonio per visualizzare nome, paese, periodo storico e parole chiave.": "Click on a heritage site to view its name, country, historical period and keywords.",
    "Apri scheda item": "Open item record",
    "↑ Top": "↑ Top",
    "Cerca per nome, luogo, tema…": "Search by name, place, theme…",
    "Shudao": "Shudao",
    "Palazzo d’Estate": "Summer Palace",
    "Giardini classici di Suzhou": "Classical Gardens of Suzhou",
    "Venezia e la sua Laguna": "Venice and its Lagoon",
    "Via Appia. Regina Viarum": "Via Appia. Regina Viarum",
    "Villa d’Este, Tivoli": "Villa d’Este, Tivoli",
    "Vie storiche": "Historic routes",
    "Giardini e acqua": "Gardens and water",
    "Città d’acqua e giardini": "Water cities and gardens",
    "Una rete digitale per descrivere, navigare e interpretare le relazioni fra siti culturali cinesi e italiani: vie storiche, giardini d’acqua e città d’acqua.": "A digital network for describing, navigating and interpreting relations between Chinese and Italian cultural sites: historic routes, water gardens and water cities.",
    "Esplora il catalogo": "Explore the catalogue",
    "Apri la mappa": "Open the map",
    "Idea del progetto": "Project idea",
    "Il progetto non presenta soltanto sei luoghi patrimoniali: li trasforma in una collezione digitale strutturata, composta da item, metadati, fonti autorevoli, dati geografici e relazioni tipizzate.": "The project does not simply present six heritage places: it transforms them into a structured digital collection made of items, metadata, authoritative sources, geographic data and typed relations.",
    "Progetto didattico per Digital Humanities e Patrimonio Culturale.": "Course project for Digital Humanities and Cultural Heritage."
  }
};

/* --- Full-page translation extension: long paragraphs and item pages --- */
Object.assign(I18N.zh, {
  "Salta al contenuto": "跳至正文",
  "Menu": "菜单",
  "Digital Humanities · Patrimonio Culturale · Cina–Italia": "数字人文 · 文化遗产 · 中国—意大利",
  "Le tre coppie patrimoniali di questo sito non nascono come semplici somiglianze visive: si collocano nel quadro più ampio della cooperazione culturale tra Cina e Italia, costruita attraverso dialoghi istituzionali, forum dedicati ai siti UNESCO e pratiche di gemellaggio fra siti e città.": "本网站中的三组遗产配对并不是简单的视觉相似性，而是置于中意文化合作的更大框架之中：这一框架由制度性对话、面向 UNESCO 遗产地的论坛，以及遗产地与城市之间的结好实践共同构成。",
  "In questo progetto il": "在本项目中，",
  "gemellaggio": "结好关系",
  "è inteso come una relazione di cooperazione, confronto e reciproca valorizzazione. Il sito traduce questa cornice in una collezione digitale strutturata, fatta di": "被理解为一种合作、比较与相互赋值的文化关系。本网站将这一框架转化为一个结构化数字集合，由",
  "item, metadati, fonti autorevoli, coordinate geografiche e relazioni tipizzate": "条目、元数据、权威来源、地理坐标和类型化关系",
  "Dallo storico rapporto Venezia–Suzhou fino a esempi più recenti come Procida–Dujiangyan, la cooperazione si sviluppa anche a livello civico e territoriale. Secondo il Ministero degli Affari Esteri della Repubblica Popolare Cinese, ad aprile 2026 Cina e Italia hanno stabilito": "从威尼斯—苏州的历史性关系，到普罗奇达—都江堰等较新的案例，中意合作也在城市与地方层面持续展开。根据中华人民共和国外交部资料，截至2026年4月，中国和意大利已建立",
  "91 coppie di relazioni amichevoli": "91 对友好关系",
  "tra province, città e regioni.": "，涉及省、市和地区。",
  "Il tema della cooperazione culturale rientra nel quadro dei rapporti bilaterali Cina–Italia, rafforzando lo sfondo istituzionale entro cui leggere i gemellaggi patrimoniali.": "文化合作议题属于中意双边关系框架的一部分，为理解遗产结好关系提供了制度背景。",
  "Forum Cina–Italia per i gemellaggi tra i siti del patrimonio culturale mondiale UNESCO": "中意世界文化遗产地结好论坛",
  "approfondisce il dialogo tra istituzioni, esperti e territori.": "深化了机构、专家与地方之间的对话。",
  "Forum Culturale Italia–Cina": "意中文化论坛",
  "rilancia il dialogo tra i siti UNESCO dei due Paesi e presenta il gemellaggio come strumento di confronto culturale e promozione condivisa.": "重新推动两国 UNESCO 遗产地之间的对话，并将结好关系呈现为文化比较与共同推广的工具。",
  "lo": "将",
  "è trattato correttamente come risorsa in": "准确地作为",
  ", non come sito già iscritto. Per questo la relazione con la": "处理，而不是作为已经正式列入名录的世界遗产。因此，它与",
  "è usata soprattutto come confronto interpretativo nel quadro generale dei gemellaggi Cina–Italia.": "的关系主要被用作中意结好关系总体框架下的解释性比较。",
  "Cornice politica": "政治框架",
  "Colloquio dei capi e cooperazione bilaterale": "高层会谈与双边合作",
  "Il dialogo tra i vertici istituzionali fornisce il quadro politico entro cui si collocano anche gli scambi culturali e patrimoniali tra Cina e Italia.": "高层制度性对话为中意文化与遗产交流提供了政治框架。",
  "Fonte ufficiale: Governo cinese / gov.cn": "官方来源：中国政府网 / gov.cn",
  "UNESCO Italia": "意大利 UNESCO 委员会",
  "Il Forum Culturale Italia–Cina lancia il gemellaggio tra i siti UNESCO": "意中文化论坛启动 UNESCO 遗产地结好",
  "Uno dei passaggi chiave per la costruzione di una rete di relazioni tra patrimoni dei due Paesi.": "这是构建两国遗产关系网络的关键节点之一。",
  "Fonte: Commissione Nazionale Italiana per l’UNESCO": "来源：意大利 UNESCO 全国委员会",
  "Forum Cina–Italia per i gemellaggi tra i siti UNESCO": "中意 UNESCO 遗产地结好论坛",
  "Il forum di Hangzhou consolida lo scambio di esperienze e di pratiche di tutela tra siti patrimoniali cinesi e italiani.": "杭州论坛巩固了中意遗产地之间关于经验与保护实践的交流。",
  "Fonte: China News / 凤凰网": "来源：中国新闻网 / 凤凰网",
  "Caso studio": "案例研究",
  "Siti UNESCO": "UNESCO 遗产地",
  "Villa d’Este ↔ Palazzo d’Estate": "埃斯特别墅 ↔ 颐和园",
  "Un gemellaggio esplicitamente formulato tra due paesaggi d’acqua e di rappresentazione del potere.": "这是两个水景与权力表征景观之间被明确提出的结好案例。",
  "Fonte: Visit Lazio": "来源：Visit Lazio",
  "Mostra / evento": "展览 / 活动",
  "Dove il cielo incontra l’umano: il Palazzo d’Estate di Pechino a Villa d’Este": "天人合一：北京颐和园走进埃斯特别墅",
  "Questa iniziativa espositiva rende visibile il dialogo culturale tra i due siti anche sul piano curatoriale e pubblico, trasformando il gemellaggio in esperienza culturale condivisa.": "这一展览活动使两处遗产地之间的文化对话在策展与公共传播层面变得可见，并将结好关系转化为共享的文化体验。",
  "Fonte: Artribune": "来源：Artribune",
  "Gemellaggio civico": "城市结好",
  "Suzhou ↔ Venezia": "苏州 ↔ 威尼斯",
  "Il rapporto tra Suzhou e Venezia mostra come la cooperazione Cina–Italia passi anche attraverso legami urbani di lunga durata.": "苏州与威尼斯的关系表明，中意合作也通过长期的城市关系得以延续。",
  "Fonte ufficiale: Comune di Venezia": "官方来源：威尼斯市政府",
  "Esempio recente": "近期案例",
  "Procida ↔ Dujiangyan": "普罗奇达 ↔ 都江堰",
  "Un esempio recente di gemellaggio territoriale che rende visibile la continuità e l’attualità degli scambi culturali tra i due Paesi.": "这是一个近期的地方结好案例，体现了两国文化交流的延续性与现实性。",
  "Fonte: notizia illustrativa fornita dall’utente": "来源：用户提供的说明性新闻材料",
  "Sistema antico di vie montane tra Cina centrale e Sichuan": "连接中国中部与四川的古代山地道路系统",
  "La più antica e importante delle grandi strade romane": "古罗马最古老、最重要的大道之一",
  "Giardino imperiale di Pechino e capolavoro del paesaggio cinese": "北京皇家园林与中国景观艺术杰作",
  "Giardino rinascimentale italiano e giardino d’acqua": "意大利文艺复兴园林与水景花园",
  "Sistema di giardini storici privati nella città di Suzhou": "苏州城内历史私家园林体系",
  "Città lagunare, sistema insulare e paesaggio culturale": "潟湖城市、岛屿系统与文化景观",
  "Card filtrabili per paese e ricerca libera.": "可按国家筛选并进行自由搜索的卡片。",
  "Punti geografici, mappe OSM e navigazione spaziale.": "地理点、OpenStreetMap 地图与空间导航。",
  "Tabella strutturata, CSV, JSON, XML/DC e TEI.": "结构化表格、CSV、JSON、XML/DC 与 TEI。",
  "costruisce una piccola collezione digitale dedicata ai rapporti culturali fra patrimoni cinesi e italiani. Ogni item è descritto attraverso metadati, fonti, coordinate e relazioni con altri item.": "构建了一个关于中意文化遗产关系的小型数字集合。每个条目都通过元数据、来源、坐标以及与其他条目的关系进行描述。",
  "La domanda guida è: come trasformare gemellaggi e analogie patrimoniali in un sistema navigabile di dati, relazioni e interpretazioni?": "本项目的核心问题是：如何将遗产结好与遗产类比转化为一个可浏览的数据、关系与解释系统？",
  "File dati:": "数据文件：",
  "/ Catalogo": "/ 目录",
  "Catalogo degli item": "条目目录",
  "Timeline della collezione | Patrimoni in Dialogo": "集合时间线 | 对话中的遗产",
  "/ Timeline": "/ 时间线",
  "Questa pagina non raccoglie semplicemente notizie: propone una navigazione temporale integrata tra iscrizioni UNESCO, gemellaggi, forum culturali, fonti istituzionali ed eventi collegati. I nodi sono ordinati cronologicamente e collegano i sei item principali alle relazioni interpretative del progetto.": "本页面并不是简单收集新闻，而是提供一种综合的时间型导航，将 UNESCO 列入、结好关系、文化论坛、制度性来源和相关事件联系起来。各节点按时间顺序排列，并将六个核心条目与项目的解释性关系连接起来。",
  "Heritage / UNESCO": "遗产 / UNESCO",
  "Gemellaggio / relazione": "结好 / 关系",
  "Forum / istituzioni": "论坛 / 机构",
  "Evento / fonte": "事件 / 来源",
  "La timeline funziona come un secondo metodo di accesso alla collezione, accanto al catalogo e alla mappa. Ogni nodo indica un momento rilevante per capire come i patrimoni, le fonti e le relazioni Cina–Italia entrano nella struttura digitale del sito.": "这条时间线与目录和地图一起，构成进入集合的第二种访问方式。每个节点都标示一个关键时刻，帮助理解遗产、来源和中意关系如何进入本网站的数字结构。",
  "Fonte istituzionale": "制度性来源",
  "Venezia e Suzhou stabiliscono un rapporto di gemellaggio": "威尼斯与苏州建立结好关系",
  "Il rapporto tra Venezia e Suzhou offre una base storica alla coppia interpretativa “città d’acqua”: due spazi urbani segnati da canali, ponti, mobilità acquea e immaginari lagunari.": "威尼斯与苏州的关系为“水城”这一解释性配对提供了历史基础：两座城市空间都由运河、桥梁、水上交通与潟湖想象所塑造。",
  "Relazione:": "关系：",
  "Fonte: Comune di Venezia": "来源：威尼斯市政府",
  "Patrimonio iscritto": "已列入遗产",
  "Venezia e la sua Laguna entra nella World Heritage List": "威尼斯及其潟湖列入世界遗产名录",
  "L’iscrizione riconosce il valore culturale del sistema urbano-lagunare veneziano, centrale per la coppia Suzhou–Venezia.": "该列入确认了威尼斯城市—潟湖系统的文化价值，这也是苏州—威尼斯配对的核心。",
  "Item collegato:": "关联条目：",
  "Fonte UNESCO": "UNESCO 来源",
  "I Giardini classici di Suzhou entrano nella World Heritage List": "苏州古典园林列入世界遗产名录",
  "L’iscrizione valorizza la tradizione dei giardini privati cinesi, intesi come microcosmi poetici di acqua, roccia, architettura e vita letteraria.": "该列入凸显了中国私家园林传统，将其理解为由水、石、建筑与文人生活构成的诗性微观世界。",
  "Il Palazzo d’Estate di Pechino entra nella World Heritage List": "北京颐和园列入世界遗产名录",
  "Il sito viene riconosciuto come capolavoro del giardino paesaggistico cinese, fondato sul dialogo tra lago, collina, architettura e paesaggio simbolico.": "该遗产地被认定为中国景观园林的杰作，其核心在于湖泊、山体、建筑与象征性景观之间的对话。",
  "Villa d’Este, Tivoli entra nella World Heritage List": "蒂沃利埃斯特别墅列入世界遗产名录",
  "L’iscrizione riconosce l’eccezionale valore del giardino rinascimentale e del suo sistema scenografico di fontane, acqua e architettura.": "该列入确认了这座文艺复兴园林及其喷泉、水景与建筑舞台化系统的突出价值。",
  "Questo nodo introduce il gemellaggio come dispositivo culturale e istituzionale: non solo somiglianza estetica tra luoghi, ma forma di cooperazione e promozione reciproca.": "该节点将结好关系引入为一种文化与制度装置：它不仅是地点之间的审美相似性，更是一种合作与相互推广的形式。",
  "Funzione nel progetto:": "在项目中的功能：",
  "contesto istituzionale dei gemellaggi patrimoniali.": "遗产结好关系的制度背景。",
  "Lista Tentativa": "预备名单",
  "Status patrimoniale": "遗产状态",
  "Shudao è documentato nella Lista Tentativa UNESCO": "蜀道被记录在 UNESCO 预备名单中",
  "Nel progetto lo Shudao non viene presentato come sito già iscritto, ma come risorsa in Lista Tentativa. Questa distinzione rende più corretta la relazione interpretativa con la Via Appia.": "在本项目中，蜀道并不被呈现为已正式列入的世界遗产，而是作为预备名单资源。这一区分使其与阿皮亚古道之间的解释性关系更加准确。",
  "Cooperazione culturale": "文化合作",
  "Il forum di Hangzhou rafforza il dialogo tra istituzioni, esperti e territori. Nel progetto funziona come snodo tra le relazioni già esistenti e le nuove coppie patrimoniali.": "杭州论坛加强了机构、专家与地方之间的对话。在本项目中，它是既有关系与新遗产配对之间的枢纽。",
  "Relazioni richiamate:": "涉及的关系：",
  "Palazzo d’Estate ↔ Villa d’Este; Suzhou ↔ Venezia.": "颐和园 ↔ 埃斯特别墅；苏州 ↔ 威尼斯。",
  "La Via Appia. Regina Viarum entra nella World Heritage List": "阿皮亚古道“道路之后”列入世界遗产名录",
  "L’iscrizione consente di leggere la Via Appia come controparte italiana dello Shudao nella categoria delle vie storiche e delle infrastrutture culturali del movimento.": "这一列入使阿皮亚古道可以作为蜀道在历史道路与流动性文化基础设施类别中的意大利对应项来理解。",
  "Contesto istituzionale": "制度背景",
  "Dialogo istituzionale Cina–Italia e cooperazione culturale": "中意制度性对话与文化合作",
  "Il quadro politico e diplomatico bilaterale fornisce uno sfondo recente alla lettura dei gemellaggi e delle collaborazioni culturali tra patrimoni cinesi e italiani.": "双边政治与外交框架为理解中意遗产之间的结好与文化合作提供了近期背景。",
  "cornice istituzionale della rete.": "网络的制度框架。",
  "Fonte: gov.cn": "来源：gov.cn",
  "Gemellaggio territoriale": "地方结好",
  "Procida e Dujiangyan come esempio di continuità degli scambi": "普罗奇达与都江堰：交流延续性的案例",
  "Questo caso non fa parte dei sei item principali, ma mostra che la logica del gemellaggio e della cooperazione territoriale Cina–Italia continua ad avere attualità.": "该案例并不属于六个核心条目，但说明中意地方结好与合作逻辑仍具有现实意义。",
  "fonte di contesto, non item principale.": "背景来源，而非核心条目。",
  "Mostra": "展览",
  "L’evento espositivo rende visibile la coppia Palazzo d’Estate–Villa d’Este non solo come confronto tra siti, ma come relazione culturale attivata attraverso pratiche curatoriali e pubbliche.": "该展览事件使颐和园—埃斯特别墅这一配对不仅作为遗产地比较而存在，也作为通过策展与公共实践被激活的文化关系而可见。",
  "La cronologia non pretende di ricostruire l’intera storia delle relazioni culturali Cina–Italia. Seleziona invece i nodi temporali più utili per comprendere la collezione digitale: i sei item principali, le tre relazioni interpretative, le fonti istituzionali e gli eventi collegati.": "这条时间线并不试图重建中意文化关系的完整历史，而是选择最有助于理解数字集合的时间节点：六个核心条目、三组解释性关系、制度性来源与相关事件。",
  "Dati | Patrimoni in Dialogo": "数据 | 对话中的遗产",
  "/ Dati": "/ 数据",
  "Dati strutturati e authority records": "结构化数据与权威记录",
  "La pagina esplicita il modello dati: ogni item è composto da dato + metadati, collegamenti a fonti autorevoli e riconciliazione con record esterni.": "本页面说明数据模型：每个条目由数据与元数据构成，并连接权威来源，同时与外部记录进行对齐。",
  "Nome": "名称",
  "Luogo": "地点",
  "Tipo": "类型",
  "Status": "状态",
  "Anno": "年份",
  "Criteri": "标准",
  "Coordinate": "坐标",
  "Fonte": "来源",
  "via storica / cultural route": "历史道路 / 文化线路",
  "2015 tentative": "2015 预备名单",
  "proposti: culturali": "拟议：文化类",
  "giardino imperiale": "皇家园林",
  "villa e giardino rinascimentale": "文艺复兴别墅与园林",
  "giardini classici": "古典园林",
  "1997, estensione 2000": "1997，2000 年扩展",
  "città lagunare / paesaggio culturale": "潟湖城市 / 文化景观",
  "Modello Dublin Core usato": "使用的 Dublin Core 模型",
  "Crediti immagini principali": "主要图片来源说明",
  "Le fotografie sostituiscono le illustrazioni locali e sono documentate come fonti esterne indicate dall’autrice del progetto.": "这些照片替代了本地插画，并作为项目作者标注的外部来源进行记录。",
  "Item": "条目",
  "Fonte / licenza indicata": "来源 / 标注许可",
  "Fonte immagine: Wikimedia Commons, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "图片来源：Wikimedia Commons，经 Bing Images 标注。用户标注许可：可修改、分享和使用。",
  "Fonte immagine: Flickr, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "图片来源：Flickr，经 Bing Images 标注。用户标注许可：可修改、分享和使用。",
  "Fonte immagine: Viaggia e Scopri, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "图片来源：Viaggia e Scopri，经 Bing Images 标注。用户标注许可：可修改、分享和使用。",
  "Fonte immagine: Canal Grande Venezia, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "图片来源：Canal Grande Venezia，经 Bing Images 标注。用户标注许可：可修改、分享和使用。",
  "Componenti | Patrimoni in Dialogo": "组件 | 对话中的遗产",
  "/ Componenti": "/ 组件",
  "Componenti implementati": "已实现组件",
  "Questa pagina serve per l’orale: elenca i componenti HTML/CSS/JS usati e il loro ruolo nel progetto.": "本页面用于口试说明：列出项目中使用的 HTML/CSS/JS 组件及其作用。",
  "1. Responsive top navigation": "1. 响应式顶部导航",
  "Navbar responsive con menu mobile, dropdown degli item e link a tutte le pagine.": "响应式导航栏，包含移动端菜单、条目下拉菜单和所有页面链接。",
  "2. Cards catalogo": "2. 目录卡片",
  "Card per la navigazione del catalogo; ogni card contiene immagine, status, tema e pulsante verso la scheda item.": "用于目录浏览的卡片；每张卡片包含图片、状态、主题以及通往条目页面的按钮。",
  "3. Search/filter": "3. 搜索 / 筛选",
  "Filtro JavaScript per catalogo e tabella dati.": "用于目录和数据表的 JavaScript 筛选功能。",
  "4. Modal": "4. 模态窗口",
  "Finestra modale nella home per spiegare l’idea progettuale senza abbandonare la pagina.": "首页中的模态窗口，用于在不离开页面的情况下说明项目理念。",
  "5. Accordion": "5. 折叠面板",
  "Componente espandibile usato qui per descrivere gli elementi tecnici.": "可展开组件，用于说明技术元素。",
  "6. Tabs e slideshow": "6. 标签页与轮播图",
  "Usati nelle schede item per distinguere descrizione, relazione, metadata e fonti; slideshow per la visualizzazione iconografica.": "用于条目页面中区分描述、关系、元数据和来源；轮播图用于图像展示。",
  "7. Developer tool": "7. 开发工具",
  "Integrazione di OpenStreetMap tramite iframe; file CSV/JSON/XML usabili come dati del progetto; GitHub Pages previsto per hosting.": "通过 iframe 集成 OpenStreetMap；CSV/JSON/XML 文件可作为项目数据使用；计划使用 GitHub Pages 托管。",
  "Per la presentazione:": "展示时可以说明：",
  "puoi dire che il sito usa HTML5, CSS, JavaScript vanilla, metadati Dublin Core in head, XML/DC, un esempio TEI e riconciliazione tramite UNESCO/Wikidata/GeoNames.": "你可以说本网站使用 HTML5、CSS、原生 JavaScript、head 中的 Dublin Core 元数据、XML/DC、一个 TEI 示例，并通过 UNESCO/Wikidata/GeoNames 进行记录对齐。",
  "Mappa | Patrimoni in Dialogo": "地图 | 对话中的遗产",
  "/ Mappa": "/ 地图",
  "Questa pagina presenta una mappa eurasiatica locale più chiara, con confini nazionali e coste, e conserva sotto le sei mappe dettagliate OpenStreetMap. Le stelle indicano i sei patrimoni; le linee curve evidenziano i tre gemellaggi Cina–Italia.": "本页面展示一张更清晰的本地欧亚地图，包含国界和海岸线，并在下方保留六张详细的 OpenStreetMap 地图。五角星标示六处遗产，弧线突出三组中意结好关系。",
  "Mappa locale di orientamento: le stelle sono riposizionate sui rispettivi contesti geografici reali; per il dettaglio puntuale consultare le mappe OpenStreetMap sotto.": "本地定位示意图：五角星已根据相应地理语境重新定位；精确位置请查看下方 OpenStreetMap 详细地图。",
  "Interazioni disponibili: hover sulle stelle, click su ogni stella, click sulle curve di gemellaggio, movimento leggero della mappa al passaggio del mouse. Le mappe dettagliate sottostanti usano OpenStreetMap e richiedono connessione internet.": "可用互动：悬停五角星、点击每个五角星、点击结好弧线、鼠标经过时地图轻微移动。下方详细地图使用 OpenStreetMap，需要网络连接。",
  "Shudao 蜀道 ↔ Via Appia": "蜀道 ↔ 阿皮亚古道",
  "Due vie storiche che trasformano il territorio in infrastruttura culturale: passaggi montani, tracciati militari, commercio e memoria del movimento.": "两条历史道路都将地域转化为文化基础设施：山地通道、军事路线、贸易和流动记忆。",
  "Due paesaggi d’acqua e potere: il giardino come dispositivo estetico, politico e simbolico.": "两处水与权力的景观：园林作为审美、政治与象征装置。",
  "Due culture urbane dell’acqua: canali, giardini, laguna, forme di vita e immaginari della città liquida.": "两种水上城市文化：运河、园林、潟湖、生活方式与“流动城市”的想象。",
  "Queste sei mappe localizzano ogni item separatamente. Sono mantenute come secondo livello di consultazione, più preciso rispetto alla mappa eurasiatica di sintesi.": "这六张地图分别定位每个条目，作为比欧亚综合地图更精确的第二层查询方式。",
  "Apri in OpenStreetMap": "在 OpenStreetMap 中打开",
  "Fotografia principale dell’item.": "条目主图。",
  "Fonte immagine": "图片来源",
  "Coordinate e localizzazione sintetica.": "坐标与简要定位。",
  "Descrizione": "描述",
  "Metadati": "元数据",
  "Fonti": "来源",
  "Contesto": "语境",
  "Status:": "状态：",
  "In relazione con:": "关联对象：",
  "Oggetti correlati": "相关对象",
  "File metadati": "元数据文件",
  "Identificatore": "标识符",
  "Titolo": "标题",
  "Tipologia": "类型",
  "Scheda UNESCO / Tentative List": "UNESCO / 预备名单页面",
  "Wikidata authority record": "Wikidata 权威记录",
  "GeoNames / luogo": "GeoNames / 地点",
  "Apri la mappa dettagliata in OpenStreetMap": "在 OpenStreetMap 中打开详细地图",
  "Lo Shudao è un sistema di strade antiche che collega la Cina centrale con il Sichuan attraverso aree montane complesse. Nel progetto è trattato come caso cinese di via storica e come patrimonio in Lista Tentativa UNESCO.": "蜀道是一套古代道路系统，穿越复杂山地，将中国中部与四川连接起来。在本项目中，它被作为中国历史道路案例和 UNESCO 预备名单遗产资源来处理。",
  "Il valore interpretativo principale è la relazione tra infrastruttura, paesaggio montano, circolazione politica e scambi culturali. Il sito consente di ragionare sul patrimonio non come monumento isolato, ma come rete di percorsi, passaggi e relazioni territoriali.": "其主要解释价值在于基础设施、山地景观、政治流通与文化交流之间的关系。该遗产使我们能够将文化遗产理解为道路、通道与地域关系网络，而非孤立纪念物。",
  "Il dialogo con la Via Appia evidenzia due modelli di strada storica: una via montana cinese segnata da passaggi, fortificazioni e adattamento al paesaggio; una via romana progettata come infrastruttura lineare di espansione, controllo e comunicazione.": "与阿皮亚古道的对话凸显了两种历史道路模式：一种是由关隘、防御设施和地形适应塑造的中国山地道路；另一种是作为扩张、控制和沟通线性基础设施而设计的罗马道路。",
  "Apri item correlato: Via Appia. Regina Viarum": "打开关联条目：阿皮亚古道",
  "La Via Appia, costruita e sviluppata a partire dal 312 a.C., fu concepita come asse strategico e divenne una infrastruttura decisiva per la crescita urbana, la produzione agricola e gli scambi. Il sito seriale UNESCO comprende tratti, monumenti, resti archeologici e paesaggi legati alla strada.": "阿皮亚古道自公元前312年开始建设和发展，最初被构想为战略轴线，并成为城市发展、农业生产与交流的关键基础设施。该 UNESCO 系列遗产包括与道路相关的路段、纪念物、考古遗存和景观。",
  "Nel progetto rappresenta il patrimonio lineare come infrastruttura storica, tecnologia della mobilità e forma materiale del potere romano.": "在本项目中，它代表线性遗产作为历史基础设施、流动技术和罗马权力的物质形式。",
  "La relazione con lo Shudao permette di confrontare due antiche vie di lunga durata e di riflettere su come strade, passaggi, territori e memorie siano trasformati in patrimonio culturale.": "与蜀道的关系使我们能够比较两条长期延续的古代道路，并思考道路、通道、地域与记忆如何被转化为文化遗产。",
  "Apri item correlato: Shudao 蜀道": "打开关联条目：蜀道",
  "Il Palazzo d’Estate fu costruito a partire dal XVIII secolo, distrutto in larga parte nel 1860 e restaurato nel 1886. UNESCO lo descrive come capolavoro della progettazione del giardino paesaggistico cinese, fondato sulla combinazione tra elementi naturali e artificiali.": "颐和园始建于18世纪，1860年大部分被毁，并于1886年重建。UNESCO 将其描述为中国景观园林设计的杰作，其核心在于自然与人工元素的结合。",
  "Nel progetto rappresenta il rapporto tra paesaggio naturale e artificio architettonico, tra potere imperiale, estetica del giardino e armonia tra uomo e natura.": "在本项目中，它代表自然景观与建筑人工之间、皇权与园林美学之间，以及人与自然和谐理念之间的关系。",
  "Il gemellaggio con Villa d’Este permette di costruire un asse comparativo tra due giardini d’acqua: Kunming Lake e le fontane di Tivoli funzionano come dispositivi paesaggistici, estetici e simbolici.": "与埃斯特别墅的结好关系使两座水景园林形成比较轴线：昆明湖与蒂沃利喷泉都作为景观、美学和象征装置发挥作用。",
  "Apri item correlato: Villa d’Este": "打开关联条目：埃斯特别墅",
  "Villa d’Este a Tivoli è uno degli esempi più completi della cultura rinascimentale italiana. Il giardino, con fontane, bacini ornamentali e dispositivi idraulici, è considerato da UNESCO un esempio unico di giardino italiano del XVI secolo.": "蒂沃利埃斯特别墅是意大利文艺复兴文化最完整的实例之一。其园林包含喷泉、装饰性水池和水力装置，被 UNESCO 视为16世纪意大利园林的独特范例。",
  "Nel progetto rappresenta il giardino come architettura dell’acqua, della meraviglia e della scenografia, ma anche come patrimonio che comunica il rapporto tra tecnica, natura e potere.": "在本项目中，它体现了作为水、奇观与舞台化建筑的园林，同时也是表达技术、自然与权力关系的遗产。",
  "Il dialogo con il Palazzo d’Estate mette in evidenza una comune centralità dell’acqua, pur in due sistemi culturali diversi: paesaggio imperiale cinese e giardino rinascimentale italiano.": "与颐和园的对话凸显了水在两个不同文化系统中的共同核心地位：中国皇家景观与意大利文艺复兴园林。",
  "Apri item correlato: Palazzo d’Estate 颐和园": "打开关联条目：颐和园",
  "I giardini classici di Suzhou hanno radici storiche antiche e raggiunsero particolare complessità tra il XVI e il XVIII secolo. Essi trasformano spazi urbani limitati in paesaggi concentrati, combinando acqua, rocce, padiglioni, vegetazione e percorsi visivi.": "苏州古典园林拥有悠久历史，并在16至18世纪达到高度复杂的发展阶段。它们将有限的城市空间转化为浓缩景观，结合水、石、亭台、植物与视觉路径。",
  "Nel progetto rappresentano la miniaturizzazione del paesaggio, la relazione fra città, acqua e spazio privato, e la capacità del giardino di produrre esperienza estetica e culturale.": "在本项目中，它们代表景观的微缩化、城市—水—私人空间之间的关系，以及园林生成审美和文化体验的能力。",
  "Il confronto con Venezia e la sua Laguna consente di leggere due culture urbane dell’acqua: Suzhou come città dei giardini e dei canali, Venezia come sistema urbano-lagunare.": "与威尼斯及其潟湖的比较使我们能够理解两种水上城市文化：苏州作为园林与运河之城，威尼斯作为城市—潟湖系统。",
  "Apri item correlato: Venezia e la sua Laguna": "打开关联条目：威尼斯及其潟湖",
  "Venezia e la sua Laguna costituiscono un sistema patrimoniale nel quale città, isole, acqua, architetture e pratiche storiche sono inseparabili. UNESCO sottolinea l’integrità del rapporto tra insediamento umano e ambiente lagunare.": "威尼斯及其潟湖构成一个遗产系统，其中城市、岛屿、水体、建筑与历史实践密不可分。UNESCO 强调人类聚落与潟湖环境之间关系的完整性。",
  "Nel progetto rappresenta il patrimonio come ecosistema storico e urbano, fragile e complesso, in cui la conservazione riguarda insieme architettura, ambiente, mobilità e vita sociale.": "在本项目中，它代表作为历史与城市生态系统的文化遗产：脆弱而复杂，其保护同时涉及建筑、环境、交通与社会生活。",
  "Il dialogo con Suzhou permette di accostare due immagini di città d’acqua: Venezia come città-laguna e Suzhou come città dei giardini e dei canali.": "与苏州的对话使两种水城意象得以并置：威尼斯作为潟湖城市，苏州作为园林与运河之城。",
  "Apri item correlato: Giardini classici di Suzhou 苏州古典园林": "打开关联条目：苏州古典园林"
});
Object.assign(I18N.en, {
  "Salta al contenuto": "Skip to content",
  "Menu": "Menu",
  "Digital Humanities · Patrimonio Culturale · Cina–Italia": "Digital Humanities · Cultural Heritage · China–Italy",
  "Le tre coppie patrimoniali di questo sito non nascono come semplici somiglianze visive: si collocano nel quadro più ampio della cooperazione culturale tra Cina e Italia, costruita attraverso dialoghi istituzionali, forum dedicati ai siti UNESCO e pratiche di gemellaggio fra siti e città.": "The three heritage pairs in this site are not based merely on visual resemblance; they are situated within the broader framework of China–Italy cultural cooperation, built through institutional dialogues, forums dedicated to UNESCO sites, and twinning practices between sites and cities.",
  "In questo progetto il": "In this project,",
  "gemellaggio": "twinning",
  "è inteso come una relazione di cooperazione, confronto e reciproca valorizzazione. Il sito traduce questa cornice in una collezione digitale strutturata, fatta di": "is understood as a relation of cooperation, comparison and mutual valorisation. The site translates this framework into a structured digital collection made of",
  "item, metadati, fonti autorevoli, coordinate geografiche e relazioni tipizzate": "items, metadata, authoritative sources, geographic coordinates and typed relations",
  "Dallo storico rapporto Venezia–Suzhou fino a esempi più recenti come Procida–Dujiangyan, la cooperazione si sviluppa anche a livello civico e territoriale. Secondo il Ministero degli Affari Esteri della Repubblica Popolare Cinese, ad aprile 2026 Cina e Italia hanno stabilito": "From the historical Venice–Suzhou relationship to more recent cases such as Procida–Dujiangyan, cooperation also develops at civic and territorial levels. According to the Ministry of Foreign Affairs of the People’s Republic of China, as of April 2026 China and Italy had established",
  "91 coppie di relazioni amichevoli": "91 pairs of friendly relations",
  "tra province, città e regioni.": "between provinces, cities and regions.",
  "Il tema della cooperazione culturale rientra nel quadro dei rapporti bilaterali Cina–Italia, rafforzando lo sfondo istituzionale entro cui leggere i gemellaggi patrimoniali.": "Cultural cooperation belongs to the framework of China–Italy bilateral relations and strengthens the institutional background for reading heritage twinnings.",
  "Forum Cina–Italia per i gemellaggi tra i siti del patrimonio culturale mondiale UNESCO": "China–Italy Forum for Twinnings between UNESCO World Heritage Sites",
  "approfondisce il dialogo tra istituzioni, esperti e territori.": "deepens the dialogue among institutions, experts and territories.",
  "Forum Culturale Italia–Cina": "Italy–China Cultural Forum",
  "rilancia il dialogo tra i siti UNESCO dei due Paesi e presenta il gemellaggio come strumento di confronto culturale e promozione condivisa.": "relaunches dialogue between the UNESCO sites of the two countries and presents twinning as a tool for cultural comparison and shared promotion.",
  "lo": "",
  "è trattato correttamente come risorsa in": "is correctly treated as a resource in",
  ", non come sito già iscritto. Per questo la relazione con la": "rather than as an already inscribed site. For this reason, the relation with",
  "è usata soprattutto come confronto interpretativo nel quadro generale dei gemellaggi Cina–Italia.": "is used mainly as an interpretive comparison within the broader framework of China–Italy twinnings.",
  "Cornice politica": "Political framework",
  "Colloquio dei capi e cooperazione bilaterale": "Leaders’ meeting and bilateral cooperation",
  "Il dialogo tra i vertici istituzionali fornisce il quadro politico entro cui si collocano anche gli scambi culturali e patrimoniali tra Cina e Italia.": "Dialogue at the highest institutional level provides the political framework for cultural and heritage exchanges between China and Italy.",
  "Fonte ufficiale: Governo cinese / gov.cn": "Official source: Chinese Government / gov.cn",
  "UNESCO Italia": "UNESCO Italy",
  "Il Forum Culturale Italia–Cina lancia il gemellaggio tra i siti UNESCO": "The Italy–China Cultural Forum launches twinning between UNESCO sites",
  "Uno dei passaggi chiave per la costruzione di una rete di relazioni tra patrimoni dei due Paesi.": "One of the key steps in building a network of relations between the two countries’ heritage sites.",
  "Fonte: Commissione Nazionale Italiana per l’UNESCO": "Source: Italian National Commission for UNESCO",
  "Forum Cina–Italia per i gemellaggi tra i siti UNESCO": "China–Italy Forum for Twinnings between UNESCO Sites",
  "Il forum di Hangzhou consolida lo scambio di esperienze e di pratiche di tutela tra siti patrimoniali cinesi e italiani.": "The Hangzhou Forum consolidates the exchange of experiences and conservation practices between Chinese and Italian heritage sites.",
  "Fonte: China News / 凤凰网": "Source: China News / ifeng.com",
  "Caso studio": "Case study",
  "Siti UNESCO": "UNESCO sites",
  "Villa d’Este ↔ Palazzo d’Estate": "Villa d’Este ↔ Summer Palace",
  "Un gemellaggio esplicitamente formulato tra due paesaggi d’acqua e di rappresentazione del potere.": "An explicitly formulated twinning between two water landscapes and representations of power.",
  "Fonte: Visit Lazio": "Source: Visit Lazio",
  "Mostra / evento": "Exhibition / event",
  "Dove il cielo incontra l’umano: il Palazzo d’Estate di Pechino a Villa d’Este": "Where Heaven Meets the Human: Beijing Summer Palace at Villa d’Este",
  "Questa iniziativa espositiva rende visibile il dialogo culturale tra i due siti anche sul piano curatoriale e pubblico, trasformando il gemellaggio in esperienza culturale condivisa.": "This exhibition initiative makes the cultural dialogue between the two sites visible at the curatorial and public level, transforming twinning into a shared cultural experience.",
  "Fonte: Artribune": "Source: Artribune",
  "Gemellaggio civico": "Civic twinning",
  "Suzhou ↔ Venezia": "Suzhou ↔ Venice",
  "Il rapporto tra Suzhou e Venezia mostra come la cooperazione Cina–Italia passi anche attraverso legami urbani di lunga durata.": "The relation between Suzhou and Venice shows how China–Italy cooperation also operates through long-standing urban links.",
  "Fonte ufficiale: Comune di Venezia": "Official source: City of Venice",
  "Esempio recente": "Recent example",
  "Procida ↔ Dujiangyan": "Procida ↔ Dujiangyan",
  "Un esempio recente di gemellaggio territoriale che rende visibile la continuità e l’attualità degli scambi culturali tra i due Paesi.": "A recent example of territorial twinning that makes visible the continuity and current relevance of cultural exchanges between the two countries.",
  "Fonte: notizia illustrativa fornita dall’utente": "Source: illustrative news item provided by the user",
  "Sistema antico di vie montane tra Cina centrale e Sichuan": "Ancient system of mountain routes between central China and Sichuan",
  "La più antica e importante delle grandi strade romane": "The oldest and most important of the great Roman roads",
  "Giardino imperiale di Pechino e capolavoro del paesaggio cinese": "Imperial garden in Beijing and masterpiece of Chinese landscape design",
  "Giardino rinascimentale italiano e giardino d’acqua": "Italian Renaissance garden and water garden",
  "Sistema di giardini storici privati nella città di Suzhou": "System of historic private gardens in the city of Suzhou",
  "Città lagunare, sistema insulare e paesaggio culturale": "Lagoon city, island system and cultural landscape",
  "Card filtrabili per paese e ricerca libera.": "Cards filterable by country and free search.",
  "Punti geografici, mappe OSM e navigazione spaziale.": "Geographic points, OSM maps and spatial navigation.",
  "Tabella strutturata, CSV, JSON, XML/DC e TEI.": "Structured table, CSV, JSON, XML/DC and TEI.",
  "costruisce una piccola collezione digitale dedicata ai rapporti culturali fra patrimoni cinesi e italiani. Ogni item è descritto attraverso metadati, fonti, coordinate e relazioni con altri item.": "builds a small digital collection dedicated to cultural relations between Chinese and Italian heritage sites. Each item is described through metadata, sources, coordinates and relations with other items.",
  "La domanda guida è: come trasformare gemellaggi e analogie patrimoniali in un sistema navigabile di dati, relazioni e interpretazioni?": "The guiding question is: how can heritage twinnings and analogies be transformed into a navigable system of data, relations and interpretations?",
  "File dati:": "Data files:",
  "/ Catalogo": "/ Catalogue",
  "Timeline della collezione | Patrimoni in Dialogo": "Collection Timeline | Heritages in Dialogue",
  "/ Timeline": "/ Timeline",
  "Questa pagina non raccoglie semplicemente notizie: propone una navigazione temporale integrata tra iscrizioni UNESCO, gemellaggi, forum culturali, fonti istituzionali ed eventi collegati. I nodi sono ordinati cronologicamente e collegano i sei item principali alle relazioni interpretative del progetto.": "This page does not simply collect news: it offers integrated temporal navigation across UNESCO inscriptions, twinnings, cultural forums, institutional sources and related events. The nodes are ordered chronologically and connect the six main items to the project’s interpretive relations.",
  "Heritage / UNESCO": "Heritage / UNESCO",
  "Gemellaggio / relazione": "Twinning / relation",
  "Forum / istituzioni": "Forum / institutions",
  "Evento / fonte": "Event / source",
  "La timeline funziona come un secondo metodo di accesso alla collezione, accanto al catalogo e alla mappa. Ogni nodo indica un momento rilevante per capire come i patrimoni, le fonti e le relazioni Cina–Italia entrano nella struttura digitale del sito.": "The timeline functions as a second access method to the collection, alongside the catalogue and the map. Each node marks a relevant moment for understanding how the heritage sites, sources and China–Italy relations enter the digital structure of the website.",
  "Fonte istituzionale": "Institutional source",
  "Venezia e Suzhou stabiliscono un rapporto di gemellaggio": "Venice and Suzhou establish a twinning relationship",
  "Il rapporto tra Venezia e Suzhou offre una base storica alla coppia interpretativa “città d’acqua”: due spazi urbani segnati da canali, ponti, mobilità acquea e immaginari lagunari.": "The relationship between Venice and Suzhou provides a historical basis for the interpretive pair “water cities”: two urban spaces shaped by canals, bridges, water mobility and lagoon imaginaries.",
  "Relazione:": "Relation:",
  "Fonte: Comune di Venezia": "Source: City of Venice",
  "Patrimonio iscritto": "Inscribed heritage",
  "Venezia e la sua Laguna entra nella World Heritage List": "Venice and its Lagoon enters the World Heritage List",
  "L’iscrizione riconosce il valore culturale del sistema urbano-lagunare veneziano, centrale per la coppia Suzhou–Venezia.": "The inscription recognises the cultural value of Venice’s urban-lagoon system, central to the Suzhou–Venice pair.",
  "Item collegato:": "Linked item:",
  "Fonte UNESCO": "UNESCO source",
  "I Giardini classici di Suzhou entrano nella World Heritage List": "The Classical Gardens of Suzhou enter the World Heritage List",
  "L’iscrizione valorizza la tradizione dei giardini privati cinesi, intesi come microcosmi poetici di acqua, roccia, architettura e vita letteraria.": "The inscription highlights the tradition of Chinese private gardens, understood as poetic microcosms of water, rock, architecture and literati life.",
  "Il Palazzo d’Estate di Pechino entra nella World Heritage List": "The Summer Palace in Beijing enters the World Heritage List",
  "Il sito viene riconosciuto come capolavoro del giardino paesaggistico cinese, fondato sul dialogo tra lago, collina, architettura e paesaggio simbolico.": "The site is recognised as a masterpiece of Chinese landscape garden design, based on the dialogue between lake, hill, architecture and symbolic landscape.",
  "Villa d’Este, Tivoli entra nella World Heritage List": "Villa d’Este, Tivoli enters the World Heritage List",
  "L’iscrizione riconosce l’eccezionale valore del giardino rinascimentale e del suo sistema scenografico di fontane, acqua e architettura.": "The inscription recognises the outstanding value of the Renaissance garden and its scenic system of fountains, water and architecture.",
  "Questo nodo introduce il gemellaggio come dispositivo culturale e istituzionale: non solo somiglianza estetica tra luoghi, ma forma di cooperazione e promozione reciproca.": "This node introduces twinning as a cultural and institutional device: not only aesthetic similarity between places, but a form of cooperation and mutual promotion.",
  "Funzione nel progetto:": "Function in the project:",
  "contesto istituzionale dei gemellaggi patrimoniali.": "institutional context for heritage twinnings.",
  "Lista Tentativa": "Tentative List",
  "Status patrimoniale": "Heritage status",
  "Shudao è documentato nella Lista Tentativa UNESCO": "Shudao is documented in the UNESCO Tentative List",
  "Nel progetto lo Shudao non viene presentato come sito già iscritto, ma come risorsa in Lista Tentativa. Questa distinzione rende più corretta la relazione interpretativa con la Via Appia.": "In the project, Shudao is not presented as an already inscribed site, but as a Tentative List resource. This distinction makes the interpretive relation with the Via Appia more accurate.",
  "Cooperazione culturale": "Cultural cooperation",
  "Il forum di Hangzhou rafforza il dialogo tra istituzioni, esperti e territori. Nel progetto funziona come snodo tra le relazioni già esistenti e le nuove coppie patrimoniali.": "The Hangzhou Forum strengthens dialogue among institutions, experts and territories. In the project, it functions as a link between existing relations and new heritage pairs.",
  "Relazioni richiamate:": "Relations recalled:",
  "Palazzo d’Estate ↔ Villa d’Este; Suzhou ↔ Venezia.": "Summer Palace ↔ Villa d’Este; Suzhou ↔ Venice.",
  "La Via Appia. Regina Viarum entra nella World Heritage List": "The Via Appia. Regina Viarum enters the World Heritage List",
  "L’iscrizione consente di leggere la Via Appia come controparte italiana dello Shudao nella categoria delle vie storiche e delle infrastrutture culturali del movimento.": "The inscription allows the Via Appia to be read as the Italian counterpart to Shudao in the category of historic routes and cultural infrastructures of movement.",
  "Contesto istituzionale": "Institutional context",
  "Dialogo istituzionale Cina–Italia e cooperazione culturale": "China–Italy institutional dialogue and cultural cooperation",
  "Il quadro politico e diplomatico bilaterale fornisce uno sfondo recente alla lettura dei gemellaggi e delle collaborazioni culturali tra patrimoni cinesi e italiani.": "The bilateral political and diplomatic framework provides a recent background for reading twinnings and cultural collaborations between Chinese and Italian heritage sites.",
  "cornice istituzionale della rete.": "institutional framework of the network.",
  "Fonte: gov.cn": "Source: gov.cn",
  "Gemellaggio territoriale": "Territorial twinning",
  "Procida e Dujiangyan come esempio di continuità degli scambi": "Procida and Dujiangyan as an example of continuity in exchanges",
  "Questo caso non fa parte dei sei item principali, ma mostra che la logica del gemellaggio e della cooperazione territoriale Cina–Italia continua ad avere attualità.": "This case is not part of the six main items, but it shows that the logic of China–Italy twinning and territorial cooperation remains current.",
  "fonte di contesto, non item principale.": "contextual source, not a main item.",
  "Mostra": "Exhibition",
  "L’evento espositivo rende visibile la coppia Palazzo d’Estate–Villa d’Este non solo come confronto tra siti, ma come relazione culturale attivata attraverso pratiche curatoriali e pubbliche.": "The exhibition event makes the Summer Palace–Villa d’Este pair visible not only as a comparison between sites, but also as a cultural relation activated through curatorial and public practices.",
  "La cronologia non pretende di ricostruire l’intera storia delle relazioni culturali Cina–Italia. Seleziona invece i nodi temporali più utili per comprendere la collezione digitale: i sei item principali, le tre relazioni interpretative, le fonti istituzionali e gli eventi collegati.": "The chronology does not attempt to reconstruct the entire history of China–Italy cultural relations. Instead, it selects the temporal nodes most useful for understanding the digital collection: the six main items, the three interpretive relations, institutional sources and related events.",
  "Dati | Patrimoni in Dialogo": "Data | Heritages in Dialogue",
  "/ Dati": "/ Data",
  "Dati strutturati e authority records": "Structured Data and Authority Records",
  "La pagina esplicita il modello dati: ogni item è composto da dato + metadati, collegamenti a fonti autorevoli e riconciliazione con record esterni.": "This page makes the data model explicit: each item consists of data plus metadata, links to authoritative sources and reconciliation with external records.",
  "Nome": "Name",
  "Luogo": "Place",
  "Tipo": "Type",
  "Status": "Status",
  "Anno": "Year",
  "Criteri": "Criteria",
  "Coordinate": "Coordinates",
  "Fonte": "Source",
  "via storica / cultural route": "historic route / cultural route",
  "2015 tentative": "2015 tentative",
  "proposti: culturali": "proposed: cultural",
  "giardino imperiale": "imperial garden",
  "villa e giardino rinascimentale": "Renaissance villa and garden",
  "giardini classici": "classical gardens",
  "1997, estensione 2000": "1997, extension 2000",
  "città lagunare / paesaggio culturale": "lagoon city / cultural landscape",
  "Modello Dublin Core usato": "Dublin Core model used",
  "Crediti immagini principali": "Main image credits",
  "Le fotografie sostituiscono le illustrazioni locali e sono documentate come fonti esterne indicate dall’autrice del progetto.": "The photographs replace the local illustrations and are documented as external sources indicated by the project author.",
  "Item": "Item",
  "Fonte / licenza indicata": "Source / indicated licence",
  "Fonte immagine: Wikimedia Commons, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "Image source: Wikimedia Commons, indicated via Bing Images. Licence indicated by the user: free to modify, share and use.",
  "Fonte immagine: Flickr, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "Image source: Flickr, indicated via Bing Images. Licence indicated by the user: free to modify, share and use.",
  "Fonte immagine: Viaggia e Scopri, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "Image source: Viaggia e Scopri, indicated via Bing Images. Licence indicated by the user: free to modify, share and use.",
  "Fonte immagine: Canal Grande Venezia, indicata tramite Bing Images. Licenza indicata dall’utente: free to modify, share and use.": "Image source: Canal Grande Venezia, indicated via Bing Images. Licence indicated by the user: free to modify, share and use.",
  "Componenti | Patrimoni in Dialogo": "Components | Heritages in Dialogue",
  "/ Componenti": "/ Components",
  "Componenti implementati": "Implemented Components",
  "Questa pagina serve per l’orale: elenca i componenti HTML/CSS/JS usati e il loro ruolo nel progetto.": "This page is useful for the oral presentation: it lists the HTML/CSS/JS components used and their role in the project.",
  "1. Responsive top navigation": "1. Responsive top navigation",
  "Navbar responsive con menu mobile, dropdown degli item e link a tutte le pagine.": "Responsive navbar with mobile menu, item dropdown and links to all pages.",
  "2. Cards catalogo": "2. Catalogue cards",
  "Card per la navigazione del catalogo; ogni card contiene immagine, status, tema e pulsante verso la scheda item.": "Cards for catalogue navigation; each card contains an image, status, theme and button leading to the item record.",
  "3. Search/filter": "3. Search/filter",
  "Filtro JavaScript per catalogo e tabella dati.": "JavaScript filter for the catalogue and data table.",
  "4. Modal": "4. Modal",
  "Finestra modale nella home per spiegare l’idea progettuale senza abbandonare la pagina.": "Modal window on the home page to explain the project idea without leaving the page.",
  "5. Accordion": "5. Accordion",
  "Componente espandibile usato qui per descrivere gli elementi tecnici.": "Expandable component used here to describe the technical elements.",
  "6. Tabs e slideshow": "6. Tabs and slideshow",
  "Usati nelle schede item per distinguere descrizione, relazione, metadata e fonti; slideshow per la visualizzazione iconografica.": "Used in the item records to distinguish description, relation, metadata and sources; slideshow for iconographic display.",
  "7. Developer tool": "7. Developer tool",
  "Integrazione di OpenStreetMap tramite iframe; file CSV/JSON/XML usabili come dati del progetto; GitHub Pages previsto per hosting.": "Integration of OpenStreetMap through iframes; CSV/JSON/XML files usable as project data; GitHub Pages intended for hosting.",
  "Per la presentazione:": "For the presentation:",
  "puoi dire che il sito usa HTML5, CSS, JavaScript vanilla, metadati Dublin Core in head, XML/DC, un esempio TEI e riconciliazione tramite UNESCO/Wikidata/GeoNames.": "you can say that the site uses HTML5, CSS, vanilla JavaScript, Dublin Core metadata in the head, XML/DC, a TEI example and reconciliation through UNESCO/Wikidata/GeoNames.",
  "Mappa | Patrimoni in Dialogo": "Map | Heritages in Dialogue",
  "/ Mappa": "/ Map",
  "Questa pagina presenta una mappa eurasiatica locale più chiara, con confini nazionali e coste, e conserva sotto le sei mappe dettagliate OpenStreetMap. Le stelle indicano i sei patrimoni; le linee curve evidenziano i tre gemellaggi Cina–Italia.": "This page presents a clearer local Eurasian map with national borders and coastlines, while keeping the six detailed OpenStreetMap maps below. The stars indicate the six heritage sites; the curved lines highlight the three China–Italy twinnings.",
  "Mappa locale di orientamento: le stelle sono riposizionate sui rispettivi contesti geografici reali; per il dettaglio puntuale consultare le mappe OpenStreetMap sotto.": "Local orientation map: the stars have been repositioned within their respective real geographic contexts; for precise details, consult the OpenStreetMap maps below.",
  "Interazioni disponibili: hover sulle stelle, click su ogni stella, click sulle curve di gemellaggio, movimento leggero della mappa al passaggio del mouse. Le mappe dettagliate sottostanti usano OpenStreetMap e richiedono connessione internet.": "Available interactions: hover over the stars, click each star, click the twinning curves, and slight map movement on mouseover. The detailed maps below use OpenStreetMap and require an internet connection.",
  "Shudao 蜀道 ↔ Via Appia": "Shudao 蜀道 ↔ Via Appia",
  "Due vie storiche che trasformano il territorio in infrastruttura culturale: passaggi montani, tracciati militari, commercio e memoria del movimento.": "Two historic routes that transform territory into cultural infrastructure: mountain passes, military routes, trade and the memory of movement.",
  "Due paesaggi d’acqua e potere: il giardino come dispositivo estetico, politico e simbolico.": "Two landscapes of water and power: the garden as an aesthetic, political and symbolic device.",
  "Due culture urbane dell’acqua: canali, giardini, laguna, forme di vita e immaginari della città liquida.": "Two urban cultures of water: canals, gardens, lagoon, forms of life and imaginaries of the liquid city.",
  "Queste sei mappe localizzano ogni item separatamente. Sono mantenute come secondo livello di consultazione, più preciso rispetto alla mappa eurasiatica di sintesi.": "These six maps locate each item separately. They are kept as a second consultation level, more precise than the synthetic Eurasian map.",
  "Apri in OpenStreetMap": "Open in OpenStreetMap",
  "Fotografia principale dell’item.": "Main photograph of the item.",
  "Fonte immagine": "Image source",
  "Coordinate e localizzazione sintetica.": "Coordinates and synthetic location.",
  "Descrizione": "Description",
  "Metadati": "Metadata",
  "Fonti": "Sources",
  "Contesto": "Context",
  "Status:": "Status:",
  "In relazione con:": "In relation with:",
  "Oggetti correlati": "Related objects",
  "File metadati": "Metadata files",
  "Identificatore": "Identifier",
  "Titolo": "Title",
  "Tipologia": "Typology",
  "Scheda UNESCO / Tentative List": "UNESCO / Tentative List record",
  "Wikidata authority record": "Wikidata authority record",
  "GeoNames / luogo": "GeoNames / place",
  "Apri la mappa dettagliata in OpenStreetMap": "Open the detailed map in OpenStreetMap",
  "Lo Shudao è un sistema di strade antiche che collega la Cina centrale con il Sichuan attraverso aree montane complesse. Nel progetto è trattato come caso cinese di via storica e come patrimonio in Lista Tentativa UNESCO.": "Shudao is a system of ancient roads connecting central China with Sichuan through complex mountainous areas. In the project it is treated as a Chinese case of a historic route and as a heritage resource in the UNESCO Tentative List.",
  "Il valore interpretativo principale è la relazione tra infrastruttura, paesaggio montano, circolazione politica e scambi culturali. Il sito consente di ragionare sul patrimonio non come monumento isolato, ma come rete di percorsi, passaggi e relazioni territoriali.": "Its main interpretive value lies in the relation between infrastructure, mountain landscape, political circulation and cultural exchanges. The site allows heritage to be considered not as an isolated monument, but as a network of routes, passages and territorial relations.",
  "Il dialogo con la Via Appia evidenzia due modelli di strada storica: una via montana cinese segnata da passaggi, fortificazioni e adattamento al paesaggio; una via romana progettata come infrastruttura lineare di espansione, controllo e comunicazione.": "The dialogue with the Via Appia highlights two models of historic road: a Chinese mountain route marked by passages, fortifications and adaptation to the landscape; and a Roman road designed as a linear infrastructure of expansion, control and communication.",
  "Apri item correlato: Via Appia. Regina Viarum": "Open related item: Via Appia. Regina Viarum",
  "La Via Appia, costruita e sviluppata a partire dal 312 a.C., fu concepita come asse strategico e divenne una infrastruttura decisiva per la crescita urbana, la produzione agricola e gli scambi. Il sito seriale UNESCO comprende tratti, monumenti, resti archeologici e paesaggi legati alla strada.": "The Via Appia, built and developed from 312 BCE onwards, was conceived as a strategic axis and became a decisive infrastructure for urban growth, agricultural production and exchange. The UNESCO serial site includes road sections, monuments, archaeological remains and landscapes linked to the road.",
  "Nel progetto rappresenta il patrimonio lineare come infrastruttura storica, tecnologia della mobilità e forma materiale del potere romano.": "In the project it represents linear heritage as historical infrastructure, technology of mobility and material form of Roman power.",
  "La relazione con lo Shudao permette di confrontare due antiche vie di lunga durata e di riflettere su come strade, passaggi, territori e memorie siano trasformati in patrimonio culturale.": "The relation with Shudao makes it possible to compare two ancient long-lasting routes and to reflect on how roads, passages, territories and memories are transformed into cultural heritage.",
  "Apri item correlato: Shudao 蜀道": "Open related item: Shudao 蜀道",
  "Il Palazzo d’Estate fu costruito a partire dal XVIII secolo, distrutto in larga parte nel 1860 e restaurato nel 1886. UNESCO lo descrive come capolavoro della progettazione del giardino paesaggistico cinese, fondato sulla combinazione tra elementi naturali e artificiali.": "The Summer Palace was built from the eighteenth century onwards, largely destroyed in 1860 and restored in 1886. UNESCO describes it as a masterpiece of Chinese landscape garden design, based on the combination of natural and artificial elements.",
  "Nel progetto rappresenta il rapporto tra paesaggio naturale e artificio architettonico, tra potere imperiale, estetica del giardino e armonia tra uomo e natura.": "In the project it represents the relation between natural landscape and architectural artifice, imperial power, garden aesthetics and harmony between human beings and nature.",
  "Il gemellaggio con Villa d’Este permette di costruire un asse comparativo tra due giardini d’acqua: Kunming Lake e le fontane di Tivoli funzionano come dispositivi paesaggistici, estetici e simbolici.": "The twinning with Villa d’Este makes it possible to build a comparative axis between two water gardens: Kunming Lake and the fountains of Tivoli function as landscape, aesthetic and symbolic devices.",
  "Apri item correlato: Villa d’Este": "Open related item: Villa d’Este",
  "Villa d’Este a Tivoli è uno degli esempi più completi della cultura rinascimentale italiana. Il giardino, con fontane, bacini ornamentali e dispositivi idraulici, è considerato da UNESCO un esempio unico di giardino italiano del XVI secolo.": "Villa d’Este in Tivoli is one of the most complete examples of Italian Renaissance culture. Its garden, with fountains, ornamental basins and hydraulic devices, is considered by UNESCO a unique example of a sixteenth-century Italian garden.",
  "Nel progetto rappresenta il giardino come architettura dell’acqua, della meraviglia e della scenografia, ma anche come patrimonio che comunica il rapporto tra tecnica, natura e potere.": "In the project it represents the garden as architecture of water, wonder and scenography, but also as heritage communicating the relation between technique, nature and power.",
  "Il dialogo con il Palazzo d’Estate mette in evidenza una comune centralità dell’acqua, pur in due sistemi culturali diversi: paesaggio imperiale cinese e giardino rinascimentale italiano.": "The dialogue with the Summer Palace highlights the shared centrality of water, even within two different cultural systems: Chinese imperial landscape and Italian Renaissance garden.",
  "Apri item correlato: Palazzo d’Estate 颐和园": "Open related item: Summer Palace 颐和园",
  "I giardini classici di Suzhou hanno radici storiche antiche e raggiunsero particolare complessità tra il XVI e il XVIII secolo. Essi trasformano spazi urbani limitati in paesaggi concentrati, combinando acqua, rocce, padiglioni, vegetazione e percorsi visivi.": "The Classical Gardens of Suzhou have ancient historical roots and reached particular complexity between the sixteenth and eighteenth centuries. They transform limited urban spaces into concentrated landscapes, combining water, rocks, pavilions, vegetation and visual paths.",
  "Nel progetto rappresentano la miniaturizzazione del paesaggio, la relazione fra città, acqua e spazio privato, e la capacità del giardino di produrre esperienza estetica e culturale.": "In the project they represent the miniaturisation of landscape, the relation between city, water and private space, and the garden’s ability to produce aesthetic and cultural experience.",
  "Il confronto con Venezia e la sua Laguna consente di leggere due culture urbane dell’acqua: Suzhou come città dei giardini e dei canali, Venezia come sistema urbano-lagunare.": "The comparison with Venice and its Lagoon allows two urban cultures of water to be read together: Suzhou as a city of gardens and canals, Venice as an urban-lagoon system.",
  "Apri item correlato: Venezia e la sua Laguna": "Open related item: Venice and its Lagoon",
  "Venezia e la sua Laguna costituiscono un sistema patrimoniale nel quale città, isole, acqua, architetture e pratiche storiche sono inseparabili. UNESCO sottolinea l’integrità del rapporto tra insediamento umano e ambiente lagunare.": "Venice and its Lagoon form a heritage system in which city, islands, water, architecture and historical practices are inseparable. UNESCO emphasises the integrity of the relationship between human settlement and the lagoon environment.",
  "Nel progetto rappresenta il patrimonio come ecosistema storico e urbano, fragile e complesso, in cui la conservazione riguarda insieme architettura, ambiente, mobilità e vita sociale.": "In the project it represents heritage as a historical and urban ecosystem, fragile and complex, where conservation concerns architecture, environment, mobility and social life together.",
  "Il dialogo con Suzhou permette di accostare due immagini di città d’acqua: Venezia come città-laguna e Suzhou come città dei giardini e dei canali.": "The dialogue with Suzhou brings together two images of water cities: Venice as a lagoon city and Suzhou as a city of gardens and canals.",
  "Apri item correlato: Giardini classici di Suzhou 苏州古典园林": "Open related item: Classical Gardens of Suzhou 苏州古典园林"
});



/* --- Extra translations for complete map page coverage --- */
Object.assign(I18N.zh, {
  "Queste sei mappe localizzano ogni item separatamente. Sono mantenute come secondo livello di consultazione, più preciso rispetto alla mappa eurasiatica di sintesi.": "这六张地图分别定位每一个条目。它们作为第二层、更精确的空间查询方式，补充上方的欧亚综合地图。",
  "Sichuan / Shaanxi / Gansu · 32.231, 105.571": "四川 / 陕西 / 甘肃 · 32.231, 105.571",
  "Lazio, Campania, Basilicata, Puglia · 41.8437, 12.5307": "拉齐奥、坎帕尼亚、巴西利卡塔、普利亚 · 41.8437, 12.5307",
  "Pechino · 39.9999, 116.2755": "北京 · 39.9999, 116.2755",
  "Tivoli, Lazio · 41.9633, 12.7963": "蒂沃利，拉齐奥 · 41.9633, 12.7963",
  "Suzhou, Jiangsu · 31.3229, 120.6267": "江苏苏州 · 31.3229, 120.6267",
  "Venezia, Veneto · 45.4408, 12.3155": "威尼斯，威尼托 · 45.4408, 12.3155",
  "Apri in OpenStreetMap": "在 OpenStreetMap 中打开",
  "Shudao 蜀道 ↔ Via Appia": "蜀道 ↔ 阿皮亚古道",
  "Palazzo d’Estate ↔ Villa d’Este": "颐和园 ↔ 埃斯特别墅",
  "Suzhou ↔ Venezia": "苏州 ↔ 威尼斯",
  "Due vie storiche che trasformano il territorio in infrastruttura culturale: passaggi montani, tracciati militari, commercio e memoria del movimento.": "两条历史道路都将地域转化为文化基础设施：山地通道、军事路线、贸易流动与移动记忆。",
  "Due paesaggi d’acqua e potere: il giardino come dispositivo estetico, politico e simbolico.": "两处水与权力的景观：园林作为审美、政治与象征装置。",
  "Due culture urbane dell’acqua: canali, giardini, laguna, forme di vita e immaginari della città liquida.": "两种水上城市文化：运河、园林、潟湖、生活方式与“流动城市”的想象。",
  "Interazioni disponibili: hover sulle stelle, click su ogni stella, click sulle curve di gemellaggio, movimento leggero della mappa al passaggio del mouse. Le mappe dettagliate sottostanti usano OpenStreetMap e richiedono connessione internet.": "可用互动：悬停五角星、点击每个五角星、点击结好弧线、鼠标经过时地图轻微移动。下方详细地图使用 OpenStreetMap，需要网络连接。",
  "Mappa locale di orientamento: le stelle sono riposizionate sui rispettivi contesti geografici reali; per il dettaglio puntuale consultare le mappe OpenStreetMap sotto.": "本地示意地图：五角星已按各自真实地理语境重新定位；精确位置请查看下方 OpenStreetMap 详细地图。",
  "Italia": "意大利",
  "Cina": "中国"
});
Object.assign(I18N.en, {
  "Queste sei mappe localizzano ogni item separatamente. Sono mantenute come secondo livello di consultazione, più preciso rispetto alla mappa eurasiatica di sintesi.": "These six maps locate each item separately. They are kept as a second, more precise consultation layer beneath the synthetic Eurasian map.",
  "Sichuan / Shaanxi / Gansu · 32.231, 105.571": "Sichuan / Shaanxi / Gansu · 32.231, 105.571",
  "Lazio, Campania, Basilicata, Puglia · 41.8437, 12.5307": "Lazio, Campania, Basilicata, Apulia · 41.8437, 12.5307",
  "Pechino · 39.9999, 116.2755": "Beijing · 39.9999, 116.2755",
  "Tivoli, Lazio · 41.9633, 12.7963": "Tivoli, Lazio · 41.9633, 12.7963",
  "Suzhou, Jiangsu · 31.3229, 120.6267": "Suzhou, Jiangsu · 31.3229, 120.6267",
  "Venezia, Veneto · 45.4408, 12.3155": "Venice, Veneto · 45.4408, 12.3155",
  "Apri in OpenStreetMap": "Open in OpenStreetMap",
  "Shudao 蜀道 ↔ Via Appia": "Shudao 蜀道 ↔ Via Appia",
  "Palazzo d’Estate ↔ Villa d’Este": "Summer Palace ↔ Villa d’Este",
  "Suzhou ↔ Venezia": "Suzhou ↔ Venice",
  "Due vie storiche che trasformano il territorio in infrastruttura culturale: passaggi montani, tracciati militari, commercio e memoria del movimento.": "Two historic routes that turn territory into cultural infrastructure: mountain passages, military roads, trade and the memory of movement.",
  "Due paesaggi d’acqua e potere: il giardino come dispositivo estetico, politico e simbolico.": "Two landscapes of water and power: the garden as an aesthetic, political and symbolic device.",
  "Due culture urbane dell’acqua: canali, giardini, laguna, forme di vita e immaginari della città liquida.": "Two urban water cultures: canals, gardens, lagoon, ways of life and imaginaries of the liquid city.",
  "Interazioni disponibili: hover sulle stelle, click su ogni stella, click sulle curve di gemellaggio, movimento leggero della mappa al passaggio del mouse. Le mappe dettagliate sottostanti usano OpenStreetMap e richiedono connessione internet.": "Available interactions: hover over the stars, click each star, click the twinning curves, and move the map slightly with the mouse. The detailed maps below use OpenStreetMap and require an internet connection.",
  "Mappa locale di orientamento: le stelle sono riposizionate sui rispettivi contesti geografici reali; per il dettaglio puntuale consultare le mappe OpenStreetMap sotto.": "Local orientation map: the stars are positioned within their respective geographic contexts; for precise details, consult the OpenStreetMap maps below.",
  "Italia": "Italy",
  "Cina": "China"
});



/* --- Extra translations for item pages complete coverage --- */
Object.assign(I18N.zh, {
  "Descrizione": "描述",
  "Relazione": "关系",
  "Metadati": "元数据",
  "Fonti": "来源",
  "Identificatore": "标识符",
  "Titolo": "标题",
  "Luogo": "地点",
  "Tipologia": "类型",
  "Status": "状态",
  "Anno": "年份",
  "Criteri": "标准",
  "Coordinate": "坐标",
  "Contesto": "语境",
  "In relazione con:": "关联对象：",
  "Oggetti correlati": "相关对象",
  "File metadati": "元数据文件",
  "Mappa": "地图",
  "Apri la mappa dettagliata in OpenStreetMap": "在 OpenStreetMap 中打开详细地图",
  "Scheda UNESCO / Tentative List": "UNESCO 页面 / 预备名单",
  "Wikidata authority record": "Wikidata 权威记录",
  "GeoNames / luogo": "GeoNames / 地点",
  "Vie storiche": "历史道路",
  "Lo Shudao è un sistema di strade antiche che collega la Cina centrale con il Sichuan attraverso aree montane complesse. Nel progetto è trattato come caso cinese di via storica e come patrimonio in Lista Tentativa UNESCO, utile per il confronto con la Via Appia sul tema della conservazione dei patrimoni lineari.": "蜀道是一套古代道路系统，穿越复杂山地，将中国中部与四川地区连接起来。在本项目中，它被作为中国历史道路案例以及 UNESCO 预备名单遗产来处理，用于与阿皮亚古道围绕线性遗产保护问题展开比较。",
  "Il valore interpretativo principale è la relazione tra infrastruttura, paesaggio montano, circolazione politica e scambi culturali. Il sito consente di ragionare sul patrimonio non come monumento isolato, ma come rete territoriale.": "其主要解释价值在于基础设施、山地景观、政治流动与文化交流之间的关系。该遗产使我们能够将遗产理解为一种地域网络，而不是孤立的纪念物。",
  "Il dialogo con la Via Appia evidenzia due modelli di strada storica: una via montana cinese segnata da passaggi, fortificazioni e adattamento al paesaggio; una via romana progettata come infrastruttura imperiale e asse di espansione.": "与阿皮亚古道的对话凸显了两种历史道路模式：一条以关隘、军事防御和对山地景观适应为特征的中国山地道路；一条作为帝国基础设施和扩张轴线而设计的罗马道路。",
  "Apri item correlato: Via Appia. Regina Viarum": "打开相关条目：阿皮亚古道 Via Appia",
  "Sichuan / Shaanxi / Gansu": "四川 / 陕西 / 甘肃",
  "via storica / cultural route": "历史道路 / 文化线路",
  "2015 tentative": "2015 年预备名单",
  "proposti: culturali": "拟议：文化标准",
  "La Via Appia, costruita e sviluppata a partire dal 312 a.C., fu concepita come asse strategico e divenne una infrastruttura decisiva per la crescita urbana, la produzione agricola e gli scambi. Il sito seriale UNESCO comprende numerosi segmenti e componenti architettoniche.": "阿皮亚古道自公元前312年开始修建和发展，被构想为一条战略轴线，并成为推动城市成长、农业生产和贸易交流的关键基础设施。该 UNESCO 系列遗产包括多个道路段落和建筑组成部分。",
  "Nel progetto rappresenta il patrimonio lineare come infrastruttura storica, tecnologia della mobilità e forma materiale del potere romano.": "在本项目中，它代表了作为历史基础设施、移动技术以及罗马权力物质形式的线性遗产。",
  "La relazione con lo Shudao permette di confrontare due antiche vie di lunga durata e di riflettere su come strade, passaggi, territori e memorie siano trasformati in patrimonio culturale.": "与蜀道的关系使我们能够比较两条长期延续的古代道路，并思考道路、通道、地域和记忆如何被转化为文化遗产。",
  "Apri item correlato: Shudao 蜀道": "打开相关条目：蜀道 Shudao",
  "Lazio, Campania, Basilicata, Puglia": "拉齐奥、坎帕尼亚、巴西利卡塔、普利亚",
  "(iii)(iv)(vi)": "(iii)(iv)(vi)",
  "Il Palazzo d’Estate fu costruito a partire dal XVIII secolo, distrutto in larga parte nel 1860 e restaurato nel 1886. UNESCO lo descrive come capolavoro della progettazione del giardino paesaggistico cinese, dove colline, acque, padiglioni, palazzi, templi e ponti formano un insieme armonico.": "颐和园始建于18世纪，1860年大部分遭到破坏，并于1886年修复。UNESCO 将其描述为中国山水园林设计的杰作，在这里，山丘、水体、亭台、宫殿、寺庙和桥梁构成了一个和谐整体。",
  "Nel progetto rappresenta il rapporto tra paesaggio naturale e artificio architettonico, tra potere imperiale, estetica del giardino e armonia tra uomo e natura.": "在本项目中，它代表自然景观与建筑人工、帝国权力、园林美学以及人与自然和谐之间的关系。",
  "Il gemellaggio con Villa d’Este permette di costruire un asse comparativo tra due giardini d’acqua: Kunming Lake e le fontane di Tivoli funzionano come dispositivi paesaggistici, estetici e simbolici.": "与埃斯特别墅的结好关系使我们能够在两处水景园林之间建立比较轴线：昆明湖与蒂沃利喷泉都作为景观、美学和象征装置发挥作用。",
  "Apri item correlato: Villa d’Este": "打开相关条目：埃斯特别墅 Villa d’Este",
  "Pechino": "北京",
  "giardino imperiale": "皇家园林",
  "(i)(ii)(iii)": "(i)(ii)(iii)",
  "Villa d’Este a Tivoli è uno degli esempi più completi della cultura rinascimentale italiana. Il giardino, con fontane, bacini ornamentali e dispositivi idraulici, è considerato da UNESCO un esempio unico di giardino italiano del XVI secolo.": "蒂沃利的埃斯特别墅是意大利文艺复兴文化最完整的案例之一。其园林通过喷泉、装饰性水池和水力装置，被 UNESCO 视为16世纪意大利园林的独特范例。",
  "Nel progetto rappresenta il giardino come architettura dell’acqua, della meraviglia e della scenografia, ma anche come patrimonio che comunica il rapporto tra tecnica, natura e potere.": "在本项目中，它代表作为水、奇观与舞台化空间建筑的园林，同时也作为一种传达技术、自然与权力关系的遗产。",
  "Il dialogo con il Palazzo d’Estate mette in evidenza una comune centralità dell’acqua, pur in due sistemi culturali diversi: paesaggio imperiale cinese e giardino rinascimentale italiano.": "与颐和园的对话凸显了两种不同文化系统中水的共同中心性：中国皇家景观与意大利文艺复兴园林。",
  "Apri item correlato: Palazzo d’Estate 颐和园": "打开相关条目：颐和园 Palazzo d’Estate",
  "Tivoli, Lazio": "蒂沃利，拉齐奥",
  "villa e giardino rinascimentale": "文艺复兴别墅与园林",
  "(i)(ii)(iii)(iv)(vi)": "(i)(ii)(iii)(iv)(vi)",
  "I giardini classici di Suzhou hanno radici storiche antiche e raggiunsero particolare complessità tra il XVI e il XVIII secolo. Essi trasformano spazi urbani limitati in paesaggi concentrati, combinando acqua, rocce, architetture, piante e percorsi visivi.": "苏州古典园林具有悠久的历史根基，并在16至18世纪达到高度复杂的发展阶段。它们将有限的城市空间转化为浓缩景观，综合水体、山石、建筑、植物和视觉路径。",
  "Nel progetto rappresentano la miniaturizzazione del paesaggio, la relazione fra città, acqua e spazio privato, e la capacità del giardino di produrre esperienza estetica e culturale.": "在本项目中，它们代表景观的微缩化、城市—水—私人空间之间的关系，以及园林生产审美和文化经验的能力。",
  "Il confronto con Venezia e la sua Laguna consente di leggere due culture urbane dell’acqua: Suzhou come città dei giardini e dei canali, Venezia come sistema urbano-lagunare.": "与威尼斯及其潟湖的比较，使我们能够理解两种水上城市文化：苏州作为园林与运河之城，威尼斯作为城市—潟湖系统。",
  "Apri item correlato: Venezia e la sua Laguna": "打开相关条目：威尼斯及其潟湖",
  "Suzhou, Jiangsu": "江苏苏州",
  "giardini classici": "古典园林",
  "1997, estensione 2000": "1997 年，2000 年扩展",
  "(i)(ii)(iii)(iv)(v)": "(i)(ii)(iii)(iv)(v)",
  "Venezia e la sua Laguna costituiscono un sistema patrimoniale nel quale città, isole, acqua, architetture e pratiche storiche sono inseparabili. UNESCO sottolinea l’integrità del rapporto tra insediamento urbano e paesaggio lagunare.": "威尼斯及其潟湖构成了一个城市、岛屿、水体、建筑和历史实践不可分割的遗产系统。UNESCO 强调了城市聚落与潟湖景观之间关系的完整性。",
  "Nel progetto rappresenta il patrimonio come ecosistema storico e urbano, fragile e complesso, in cui la conservazione riguarda insieme architettura, ambiente, mobilità e vita sociale.": "在本项目中，它代表作为历史与城市生态系统的遗产：脆弱而复杂，其保护同时涉及建筑、环境、移动性和社会生活。",
  "Il dialogo con Suzhou permette di accostare due immagini di città d’acqua: Venezia come città-laguna e Suzhou come città dei giardini e dei canali.": "与苏州的对话使两种水城形象得以并置：威尼斯作为潟湖城市，苏州作为园林与运河之城。",
  "Apri item correlato: Giardini classici di Suzhou 苏州古典园林": "打开相关条目：苏州古典园林",
  "Venezia, Veneto": "威尼斯，威尼托",
  "città lagunare / paesaggio culturale": "潟湖城市 / 文化景观",
  "(i)(ii)(iii)(iv)(v)(vi)": "(i)(ii)(iii)(iv)(v)(vi)",
  "Cina": "中国",
  "Italia": "意大利",
  "Patrimonio Mondiale UNESCO": "UNESCO 世界遗产",
  "Lista Tentativa UNESCO": "UNESCO 预备名单",
  "Shudao": "蜀道 Shudao",
  "Via Appia. Regina Viarum": "阿皮亚古道 Via Appia",
  "Palazzo d’Estate": "颐和园 Palazzo d’Estate",
  "Villa d’Este": "埃斯特别墅 Villa d’Este",
  "Villa d’Este, Tivoli": "埃斯特别墅 Villa d’Este",
  "Giardini classici di Suzhou": "苏州古典园林",
  "Venezia e la sua Laguna": "威尼斯及其潟湖",
  "Sistema antico di vie montane tra Cina centrale e Sichuan": "连接中国中部与四川的古代山地道路系统"
});
Object.assign(I18N.en, {
  "Descrizione": "Description",
  "Relazione": "Relation",
  "Metadati": "Metadata",
  "Fonti": "Sources",
  "Identificatore": "Identifier",
  "Titolo": "Title",
  "Luogo": "Place",
  "Tipologia": "Type",
  "Status": "Status",
  "Anno": "Year",
  "Criteri": "Criteria",
  "Coordinate": "Coordinates",
  "Contesto": "Context",
  "In relazione con:": "Related to:",
  "Oggetti correlati": "Related objects",
  "File metadati": "Metadata files",
  "Mappa": "Map",
  "Apri la mappa dettagliata in OpenStreetMap": "Open the detailed map in OpenStreetMap",
  "Scheda UNESCO / Tentative List": "UNESCO page / Tentative List",
  "Wikidata authority record": "Wikidata authority record",
  "GeoNames / luogo": "GeoNames / place",
  "Vie storiche": "Historic routes",
  "Lo Shudao è un sistema di strade antiche che collega la Cina centrale con il Sichuan attraverso aree montane complesse. Nel progetto è trattato come caso cinese di via storica e come patrimonio in Lista Tentativa UNESCO, utile per il confronto con la Via Appia sul tema della conservazione dei patrimoni lineari.": "Shudao is a system of ancient roads connecting central China with Sichuan through complex mountain areas. In this project, it is treated as a Chinese case of a historic route and as a UNESCO Tentative List heritage resource, useful for comparison with Via Appia on the conservation of linear heritage.",
  "Il valore interpretativo principale è la relazione tra infrastruttura, paesaggio montano, circolazione politica e scambi culturali. Il sito consente di ragionare sul patrimonio non come monumento isolato, ma come rete territoriale.": "Its main interpretive value lies in the relationship between infrastructure, mountain landscape, political circulation and cultural exchange. The site makes it possible to understand heritage not as an isolated monument, but as a territorial network.",
  "Il dialogo con la Via Appia evidenzia due modelli di strada storica: una via montana cinese segnata da passaggi, fortificazioni e adattamento al paesaggio; una via romana progettata come infrastruttura imperiale e asse di espansione.": "The dialogue with Via Appia highlights two models of historic road: a Chinese mountain route marked by passes, fortifications and adaptation to the landscape; and a Roman road designed as imperial infrastructure and an axis of expansion.",
  "Apri item correlato: Via Appia. Regina Viarum": "Open related item: Via Appia. Regina Viarum",
  "Sichuan / Shaanxi / Gansu": "Sichuan / Shaanxi / Gansu",
  "via storica / cultural route": "historic route / cultural route",
  "2015 tentative": "2015 tentative",
  "proposti: culturali": "proposed: cultural",
  "La Via Appia, costruita e sviluppata a partire dal 312 a.C., fu concepita come asse strategico e divenne una infrastruttura decisiva per la crescita urbana, la produzione agricola e gli scambi. Il sito seriale UNESCO comprende numerosi segmenti e componenti architettoniche.": "Via Appia, built and developed from 312 BCE, was conceived as a strategic axis and became a decisive infrastructure for urban growth, agricultural production and exchange. The UNESCO serial site includes numerous segments and architectural components.",
  "Nel progetto rappresenta il patrimonio lineare come infrastruttura storica, tecnologia della mobilità e forma materiale del potere romano.": "In the project, it represents linear heritage as historical infrastructure, technology of mobility and material form of Roman power.",
  "La relazione con lo Shudao permette di confrontare due antiche vie di lunga durata e di riflettere su come strade, passaggi, territori e memorie siano trasformati in patrimonio culturale.": "The relation with Shudao makes it possible to compare two ancient long-lasting routes and to reflect on how roads, passages, territories and memories are transformed into cultural heritage.",
  "Apri item correlato: Shudao 蜀道": "Open related item: Shudao 蜀道",
  "Lazio, Campania, Basilicata, Puglia": "Lazio, Campania, Basilicata, Apulia",
  "Il Palazzo d’Estate fu costruito a partire dal XVIII secolo, distrutto in larga parte nel 1860 e restaurato nel 1886. UNESCO lo descrive come capolavoro della progettazione del giardino paesaggistico cinese, dove colline, acque, padiglioni, palazzi, templi e ponti formano un insieme armonico.": "The Summer Palace was built from the eighteenth century, largely destroyed in 1860 and restored in 1886. UNESCO describes it as a masterpiece of Chinese landscape garden design, where hills, water, pavilions, palaces, temples and bridges form a harmonious whole.",
  "Nel progetto rappresenta il rapporto tra paesaggio naturale e artificio architettonico, tra potere imperiale, estetica del giardino e armonia tra uomo e natura.": "In the project, it represents the relationship between natural landscape and architectural artifice, imperial power, garden aesthetics and harmony between humans and nature.",
  "Il gemellaggio con Villa d’Este permette di costruire un asse comparativo tra due giardini d’acqua: Kunming Lake e le fontane di Tivoli funzionano come dispositivi paesaggistici, estetici e simbolici.": "The twinning with Villa d’Este makes it possible to build a comparative axis between two water gardens: Kunming Lake and the fountains of Tivoli function as landscape, aesthetic and symbolic devices.",
  "Apri item correlato: Villa d’Este": "Open related item: Villa d’Este",
  "Pechino": "Beijing",
  "giardino imperiale": "imperial garden",
  "Villa d’Este a Tivoli è uno degli esempi più completi della cultura rinascimentale italiana. Il giardino, con fontane, bacini ornamentali e dispositivi idraulici, è considerato da UNESCO un esempio unico di giardino italiano del XVI secolo.": "Villa d’Este in Tivoli is one of the most complete examples of Italian Renaissance culture. Its garden, with fountains, ornamental basins and hydraulic devices, is considered by UNESCO a unique example of a sixteenth-century Italian garden.",
  "Nel progetto rappresenta il giardino come architettura dell’acqua, della meraviglia e della scenografia, ma anche come patrimonio che comunica il rapporto tra tecnica, natura e potere.": "In the project, it represents the garden as an architecture of water, wonder and scenography, but also as a heritage site that communicates the relationship between technology, nature and power.",
  "Il dialogo con il Palazzo d’Estate mette in evidenza una comune centralità dell’acqua, pur in due sistemi culturali diversi: paesaggio imperiale cinese e giardino rinascimentale italiano.": "The dialogue with the Summer Palace highlights the shared centrality of water within two different cultural systems: Chinese imperial landscape and Italian Renaissance garden.",
  "Apri item correlato: Palazzo d’Estate 颐和园": "Open related item: Summer Palace 颐和园",
  "Tivoli, Lazio": "Tivoli, Lazio",
  "villa e giardino rinascimentale": "Renaissance villa and garden",
  "I giardini classici di Suzhou hanno radici storiche antiche e raggiunsero particolare complessità tra il XVI e il XVIII secolo. Essi trasformano spazi urbani limitati in paesaggi concentrati, combinando acqua, rocce, architetture, piante e percorsi visivi.": "The Classical Gardens of Suzhou have ancient historical roots and reached particular complexity between the sixteenth and eighteenth centuries. They transform limited urban spaces into concentrated landscapes, combining water, rocks, architecture, plants and visual paths.",
  "Nel progetto rappresentano la miniaturizzazione del paesaggio, la relazione fra città, acqua e spazio privato, e la capacità del giardino di produrre esperienza estetica e culturale.": "In the project, they represent the miniaturization of landscape, the relationship between city, water and private space, and the capacity of the garden to produce aesthetic and cultural experience.",
  "Il confronto con Venezia e la sua Laguna consente di leggere due culture urbane dell’acqua: Suzhou come città dei giardini e dei canali, Venezia come sistema urbano-lagunare.": "The comparison with Venice and its Lagoon allows two urban water cultures to be read together: Suzhou as a city of gardens and canals, and Venice as an urban-lagoon system.",
  "Apri item correlato: Venezia e la sua Laguna": "Open related item: Venice and its Lagoon",
  "Suzhou, Jiangsu": "Suzhou, Jiangsu",
  "giardini classici": "classical gardens",
  "1997, estensione 2000": "1997, extension 2000",
  "Venezia e la sua Laguna costituiscono un sistema patrimoniale nel quale città, isole, acqua, architetture e pratiche storiche sono inseparabili. UNESCO sottolinea l’integrità del rapporto tra insediamento urbano e paesaggio lagunare.": "Venice and its Lagoon constitute a heritage system in which city, islands, water, architecture and historical practices are inseparable. UNESCO emphasizes the integrity of the relationship between urban settlement and lagoon landscape.",
  "Nel progetto rappresenta il patrimonio come ecosistema storico e urbano, fragile e complesso, in cui la conservazione riguarda insieme architettura, ambiente, mobilità e vita sociale.": "In the project, it represents heritage as a fragile and complex historical and urban ecosystem, in which conservation concerns architecture, environment, mobility and social life together.",
  "Il dialogo con Suzhou permette di accostare due immagini di città d’acqua: Venezia come città-laguna e Suzhou come città dei giardini e dei canali.": "The dialogue with Suzhou makes it possible to bring together two images of water cities: Venice as a lagoon city and Suzhou as a city of gardens and canals.",
  "Apri item correlato: Giardini classici di Suzhou 苏州古典园林": "Open related item: Classical Gardens of Suzhou 苏州古典园林",
  "Venezia, Veneto": "Venice, Veneto",
  "città lagunare / paesaggio culturale": "lagoon city / cultural landscape",
  "Cina": "China",
  "Italia": "Italy",
  "Patrimonio Mondiale UNESCO": "UNESCO World Heritage",
  "Lista Tentativa UNESCO": "UNESCO Tentative List",
  "Shudao": "Shudao",
  "Via Appia. Regina Viarum": "Via Appia. Regina Viarum",
  "Palazzo d’Estate": "Summer Palace",
  "Villa d’Este": "Villa d’Este",
  "Villa d’Este, Tivoli": "Villa d’Este, Tivoli",
  "Giardini classici di Suzhou": "Classical Gardens of Suzhou",
  "Venezia e la sua Laguna": "Venice and its Lagoon",
  "Sistema antico di vie montane tra Cina centrale e Sichuan": "Ancient system of mountain routes between central China and Sichuan"
});



/* --- No Chinese characters in IT/EN display; Chinese names only in ZH mode --- */
Object.assign(I18N.zh, {
  "Shudao": "蜀道 Shudao",
  "Via Appia. Regina Viarum": "阿皮亚古道 Via Appia",
  "Palazzo d’Estate": "颐和园 Palazzo d’Estate",
  "Villa d’Este": "埃斯特别墅 Villa d’Este",
  "Villa d’Este, Tivoli": "埃斯特别墅 Villa d’Este",
  "Giardini classici di Suzhou": "苏州古典园林",
  "Venezia e la sua Laguna": "威尼斯及其潟湖",
  "Apri item correlato: Via Appia. Regina Viarum": "打开相关条目：阿皮亚古道 Via Appia",
  "Apri item correlato: Shudao": "打开相关条目：蜀道 Shudao",
  "Apri item correlato: Villa d’Este": "打开相关条目：埃斯特别墅 Villa d’Este",
  "Apri item correlato: Palazzo d’Estate": "打开相关条目：颐和园 Palazzo d’Estate",
  "Apri item correlato: Venezia e la sua Laguna": "打开相关条目：威尼斯及其潟湖",
  "Apri item correlato: Giardini classici di Suzhou": "打开相关条目：苏州古典园林",
  "In relazione con:": "关联对象：",
  "Sistema antico di vie montane tra Cina centrale e Sichuan": "连接中国中部与四川的古代山地道路系统",
  "Giardino imperiale di Pechino e capolavoro del paesaggio cinese": "北京皇家园林与中国山水园林杰作",
  "Sistema di giardini storici privati nella città di Suzhou": "苏州城中的历史私家园林体系",
  "Città lagunare, sistema insulare e paesaggio culturale": "潟湖城市、岛屿系统与文化景观"
});
Object.assign(I18N.en, {
  "Shudao": "Shudao",
  "Via Appia. Regina Viarum": "Via Appia. Regina Viarum",
  "Palazzo d’Estate": "Summer Palace",
  "Villa d’Este": "Villa d’Este",
  "Villa d’Este, Tivoli": "Villa d’Este, Tivoli",
  "Giardini classici di Suzhou": "Classical Gardens of Suzhou",
  "Venezia e la sua Laguna": "Venice and its Lagoon",
  "Apri item correlato: Via Appia. Regina Viarum": "Open related item: Via Appia. Regina Viarum",
  "Apri item correlato: Shudao": "Open related item: Shudao",
  "Apri item correlato: Villa d’Este": "Open related item: Villa d’Este",
  "Apri item correlato: Palazzo d’Estate": "Open related item: Summer Palace",
  "Apri item correlato: Venezia e la sua Laguna": "Open related item: Venice and its Lagoon",
  "Apri item correlato: Giardini classici di Suzhou": "Open related item: Classical Gardens of Suzhou",
  "In relazione con:": "Related to:",
  "Sistema antico di vie montane tra Cina centrale e Sichuan": "Ancient system of mountain routes between central China and Sichuan",
  "Giardino imperiale di Pechino e capolavoro del paesaggio cinese": "Imperial garden of Beijing and masterpiece of Chinese landscape design",
  "Sistema di giardini storici privati nella città di Suzhou": "System of historic private gardens in the city of Suzhou",
  "Città lagunare, sistema insulare e paesaggio culturale": "Lagoon city, island system and cultural landscape"
});



/* --- Final zh name overrides after CJK cleanup --- */
Object.assign(I18N.zh, {
  "Shudao": "蜀道 Shudao",
  "Palazzo d’Estate": "颐和园 Palazzo d’Estate",
  "Giardini classici di Suzhou": "苏州古典园林",
  "Venezia e la sua Laguna": "威尼斯及其潟湖",
  "Via Appia. Regina Viarum": "阿皮亚古道 Via Appia",
  "Villa d’Este": "埃斯特别墅 Villa d’Este",
  "Villa d’Este, Tivoli": "埃斯特别墅 Villa d’Este"
});

function normalizeI18nKey(text) {
  return text.replace(/\s+/g, ' ').trim();
}

function applyLanguage(lang) {
  const selected = ['it', 'zh', 'en'].includes(lang) ? lang : 'it';
  localStorage.setItem('preferredLanguage', selected);
  document.documentElement.setAttribute('lang', selected === 'zh' ? 'zh-CN' : selected);

  const dict = I18N[selected] || {};
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      if (['SCRIPT', 'STYLE', 'NOSCRIPT', 'IFRAME'].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
      if (!normalizeI18nKey(node.nodeValue)) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    }
  });

  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);

  nodes.forEach(node => {
    if (!node.__i18nOriginal) node.__i18nOriginal = node.nodeValue;
    const original = node.__i18nOriginal;
    const key = normalizeI18nKey(original);
    const leading = original.match(/^\s*/)[0];
    const trailing = original.match(/\s*$/)[0];

    if (selected === 'it') {
      node.nodeValue = original;
    } else if (dict[key]) {
      node.nodeValue = leading + dict[key] + trailing;
    } else {
      node.nodeValue = original;
    }
  });

  document.querySelectorAll('input[placeholder], textarea[placeholder]').forEach(el => {
    if (!el.dataset.i18nPlaceholderOriginal) el.dataset.i18nPlaceholderOriginal = el.getAttribute('placeholder') || '';
    const key = normalizeI18nKey(el.dataset.i18nPlaceholderOriginal);
    if (selected === 'it') el.setAttribute('placeholder', el.dataset.i18nPlaceholderOriginal);
    else if (dict[key]) el.setAttribute('placeholder', dict[key]);
  });

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === selected);
    btn.setAttribute('aria-pressed', btn.dataset.lang === selected ? 'true' : 'false');
  });
}

function setupLanguageSwitcher() {
  if (document.querySelector('.language-switcher')) return;
  const navlinks = document.querySelector('.navlinks');
  if (!navlinks) return;

  const switcher = document.createElement('div');
  switcher.className = 'language-switcher';
  switcher.setAttribute('aria-label', 'Language selector');
  switcher.innerHTML = `
    <button type="button" class="lang-btn" data-lang="it">IT</button>
    <button type="button" class="lang-btn" data-lang="zh">中</button>
    <button type="button" class="lang-btn" data-lang="en">EN</button>
  `;
  navlinks.appendChild(switcher);

  switcher.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLanguage(btn.dataset.lang));
  });
}

/* --- End trilingual interface --- */

